# Random Walks en Redes Multicapa de Aerolíneas

In [26]:
using Pkg

In [27]:
Pkg.add("PyPlot")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % [========>                                ]  19.3 %]  38.5 %Fetching: [======================>                  ]  53.5 %>          ]  72.7 %=====================================>   ]  92.0 %Fetching: [======================================>  ]  94.6 % Resolving package versions...
 Installed LaTeXStrings ─ v1.0.3
 Installed PyPlot ─────── v2.8.1
 Installed PyCall ─────── v1.91.2
  Updating `/Users/Yuriko/.julia/environments/v1.1/Project.toml`
  [d330b81b] + PyPlot v2.8.1
  Updating `/Users/Yuriko/.julia/environments/v1.1/Manifest.toml`
  [b964fa9f] + LaTeXStrings v1.0.3
  [438e738f] + PyCall v1.91.2
  [d330b81b] + PyPlot v2.8.1
  Building PyCall → `~/.julia/packages/PyCall/ttONZ/deps/build.log`


In [12]:
using StatsBase

In [3]:
using DelimitedFiles

In [4]:
using NamedArrays

In [5]:
using CSV

In [6]:
using LightGraphs

In [7]:
using Plots

In [190]:
using DataFrames

In [8]:
cd("$(homedir())/Documents/UNAM/Tesis_Lic")

In [9]:
pwd()

"/Users/Yuriko/Documents/UNAM/Tesis_Lic"

In [9]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

d = [0  1  0
     1  0  1
     0  0  0];

In [ ]:
m17 = readdlm("data/multi_17_du.csv", ',')

In [ ]:
multiplex17 = multiplex17[2:end, :];
multiplex17 = multiplex17[:, 2:end];

In [ ]:
multiplex = convert(Array{Int64,2}, multiplex17)

In [24]:
m17 = readdlm("data/multi_17_du.csv", ',')

3190×3190 Array{Any,2}:
 ""      "AER"   "ASF"   "CEK"   "DME"  …   "BSS"   "AEX"   "GCK"   "MGM"
 "AER"  0       0       0       1          0       0       0       0     
 "ASF"  0       0       0       1          0       0       0       0     
 "CEK"  0       0       0       1          0       0       0       0     
 "DME"  1       1       1       0          0       0       0       0     
 "EGO"  0       0       0       1       …  0       0       0       0     
 "GYD"  0       0       0       1          0       0       0       0     
 "KGD"  0       0       0       1          0       0       0       0     
 "KZN"  1       1       1       1          0       0       0       0     
 "LED"  1       1       1       1          0       0       0       0     
 "MRV"  0       1       0       1       …  0       0       0       0     
 "NBC"  0       0       0       1          0       0       0       0     
 "NJC"  0       0       0       1          0       0       0       0     
 ⋮            

In [25]:
multi17 = m17[2:end, :];
multi17 = multi17[:, 2:end];

In [26]:
multiplex17 = convert(Array{Int64,2}, multi17)

3189×3189 Array{Int64,2}:
 0  0  0  1  0  0  0  1  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  1  1  1  1  1  1  1  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  1  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  1  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  0  1  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  1  0  0  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0

In [27]:
mSA = readdlm("data/multi_SA_du.csv", ',')

935×935 Array{Any,2}:
 ""      "AOK"   "ARN"   "ATH"   "AUH"  …   "GLF"   "TMU"   "GET"   "PWM"
 "AOK"  0       0       1       0          0       0       0       0     
 "ARN"  0       0       1       0          0       0       0       0     
 "ATH"  1       1       0       1          0       0       0       0     
 "AUH"  0       0       1       0          0       0       0       0     
 "AXD"  0       0       1       0       …  0       0       0       0     
 "BCN"  0       1       1       0          0       0       0       0     
 "BEG"  0       0       1       0          0       0       0       0     
 "BOD"  0       0       0       0          0       0       0       0     
 "BRU"  0       1       1       0          0       0       0       0     
 "BUD"  0       0       1       0       …  0       0       0       0     
 "CAI"  0       0       1       1          0       0       0       0     
 "CDG"  0       1       1       0          0       0       0       0     
 ⋮              

In [28]:
multiSA = mSA[2:end, :];
multiSA = multiSA[:, 2:end];

In [29]:
multiplexSA = convert(Array{Int64,2}, multiSA)

934×934 Array{Int64,2}:
 0  0  1  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  1  0  0  1  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  1  1  1  1  0  1  1  1  1  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  0  0  0  1  0  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  1  0  0  0  1  1  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  1  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  1  0  1  0  0  1  1  0  1  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  0  0  0  1  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0  

In [30]:
mOW = readdlm("data/multi_OW_du.csv", ',')

699×699 Array{Any,2}:
 ""      "EZE"   "MIA"   "PUJ"   "ABE"  …   "SLA"   "TUC"   "IQT"   "NJC"
 "EZE"  0       1       1       0          0       0       0       0     
 "MIA"  1       0       1       0          0       0       0       0     
 "PUJ"  1       1       0       0          0       0       0       0     
 "ABE"  0       0       0       0          0       0       0       0     
 "ABQ"  0       0       0       0       …  0       0       0       0     
 "AGS"  0       0       0       0          0       0       0       0     
 "ALB"  0       0       0       0          0       0       0       0     
 "AMS"  0       0       0       0          0       0       0       0     
 "ANC"  0       0       0       0          0       0       0       0     
 "ANU"  0       1       1       0       …  0       0       0       0     
 "ASU"  1       1       0       0          0       0       0       0     
 "ATH"  0       0       0       0          0       0       0       0     
 ⋮              

In [31]:
multiOW = mOW[2:end, :];
multiOW = multiOW[:, 2:end];

In [32]:
multiplexOW = convert(Array{Int64,2}, multiOW)

698×698 Array{Int64,2}:
 0  1  1  0  0  0  0  0  0  0  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 1  0  1  0  0  0  0  0  0  1  1  0  1     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  0  0  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0  

In [211]:
in_degree(multiplexOW)

698×1 Array{Int64,2}:
 11
 96
  6
  1
  1
  1
  2
  7
  1
  7
  3
  5
  4
  ⋮
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0

In [33]:
mST = readdlm("data/multi_ST_du.csv", ',')

901×901 Array{Any,2}:
 ""      "AGF"   "AJA"   "AMS"   "AUR"  …   "AOI"   "PSA"   "PWM"   "ESB"
 "AGF"  0       0       0       0          0       0       0       0     
 "AJA"  0       0       0       0          0       0       0       0     
 "AMS"  0       0       0       0          0       0       0       0     
 "AUR"  0       0       0       0          0       0       0       0     
 "BES"  0       0       0       0       …  0       0       0       0     
 "BIA"  0       0       0       0          0       0       0       0     
 "BIQ"  0       0       0       0          0       0       0       0     
 "BLQ"  0       0       1       0          0       0       0       0     
 "BOD"  0       0       1       0          0       0       0       0     
 "BRU"  0       0       0       0       …  0       0       0       0     
 "BVE"  0       1       0       0          0       0       0       0     
 "CFE"  0       0       1       0          0       0       0       0     
 ⋮              

In [34]:
multiST = mST[2:end, :];
multiST = multiST[:, 2:end];

In [35]:
multiplexST = convert(Array{Int64,2}, multiST)

900×900 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  1  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

## Pruebas

In [36]:
rw17 = @time random_walk(multiplex17, 20, 2)

  6.348591 seconds (1.51 M allocations: 3.161 GiB, 9.91% gc time)


3189-element Array{Any,1}:
 [998 235 … 52 1222; 15 724 … 1989 51]       
 [9 478 … 448 493; 9 750 … 453 1843]         
 [244 4 … 954 620; 594 1839 … 496 497]       
 [6 340 … 404 208; 2743 232 … 195 1123]      
 [9 441 … 1351 448; 2408 728 … 1085 130]     
 [2282 727 … 1987 1345; 453 1530 … 1206 1797]
 [1527 349 … 1850 449; 1756 9 … 2335 2334]   
 [423 352 … 14 2274; 90 1033 … 472 467]      
 [358 2033 … 496 1592; 5 2408 … 727 192]     
 [1829 352 … 1059 597; 683 478 … 135 208]    
 [727 393 … 340 496; 6 662 … 191 185]        
 [14 2274 … 319 260; 14 728 … 663 487]       
 [349 1527 … 279 275; 14 3 … 168 1443]       
 ⋮                                           
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 … 0 0; 0 0 … 0 0]                      
 [0 0 …

In [80]:
rw17[1]

2×20 Array{Int64,2}:
 998  469  116  1238  1237  116  103  …  1315  1331  1299  109  1213  369
   9  682  431   470   406  550  543       74   130  2013  130   727  828

In [37]:
wl17 = @time walk_lengthP(rw17)

  0.132409 seconds (466.89 k allocations: 36.277 MiB, 1.96% gc time)


3189-element Array{Array,1}:
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 [20, 20]
 ⋮       
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  

In [89]:
rwSA = @time random_walk(multiplexSA, 40, 2)

  1.065569 seconds (798.81 k allocations: 630.442 MiB, 9.24% gc time)


934-element Array{Any,1}:
 [61 42 … 26 809; 61 1 … 126 301]      
 [16 566 … 292 322; 18 262 … 2 20]     
 [6 80 … 595 536; 34 3 … 534 11]       
 [223 4 … 25 3; 11 592 … 235 178]      
 [3 6 … 276 106; 3 71 … 73 290]        
 [89 80 … 874 263; 83 72 … 26 451]     
 [3 54 … 60 3; 26 797 … 241 175]       
 [23 16 … 181 194; 23 69 … 83 511]     
 [117 920 … 117 881; 519 839 … 279 260]
 [16 119 … 119 308; 72 581 … 102 119]  
 [20 527 … 395 119; 603 11 … 174 774]  
 [126 301 … 413 119; 11 593 … 16 73]   
 [3 52 … 176 103; 3 1 … 838 536]       
 ⋮                                     
 [132 215 … 263 45; 132 211 … 176 207] 
 [262 125 … 174 54; 117 137 … 880 87]  
 [880 263 … 126 383; 880 105 … 126 322]
 [300 295 … 173 9; 300 692 … 618 387]  
 [692 102 … 415 174; 692 300 … 358 119]
 [361 333 … 393 2; 361 396 … 408 98]   
 [396 302 … 26 557; 396 930 … 115 392] 
 [119 162 … 44 2; 396 395 … 364 296]   
 [0 0 … 0 0; 0 0 … 0 0]                
 [0 0 … 0 0; 0 0 … 0 0]                
 [0 0 … 0 0; 0

In [90]:
wlSA = @time walk_length(rwSA)

  0.079495 seconds (238.55 k allocations: 31.913 MiB, 5.06% gc time)


934-element Array{Array,1}:
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 ⋮       
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [40, 40]
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  

In [97]:
rwOW = @time random_walk(multiplexOW, 50, 2)

  0.565987 seconds (669.61 k allocations: 423.925 MiB, 9.60% gc time)


698-element Array{Any,1}:
 [89 465 … 0 0; 85 193 … 292 324]     
 [216 135 … 0 0; 202 2 … 440 193]     
 [10 271 … 607 62; 1 135 … 634 173]   
 [177 211 … 292 612; 177 30 … 89 145] 
 [61 124 … 127 347; 61 224 … 0 0]     
 [46 176 … 0 0; 46 176 … 273 401]     
 [46 57 … 290 261; 46 91 … 212 97]    
 [271 365 … 318 251; 292 12 … 105 2]  
 [178 224 … 127 361; 178 64 … 31 439] 
 [2 218 … 0 0; 3 10 … 447 437]        
 [2 210 … 31 440; 2 139 … 40 305]     
 [292 329 … 452 437; 127 46 … 335 173]
 [61 65 … 201 161; 127 324 … 379 213] 
 ⋮                                    
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               
 [0 0 … 0 0; 0 0 … 0 0]               

In [98]:
wlOW = @time walk_length(rwOW)

  0.076477 seconds (201.60 k allocations: 33.430 MiB, 12.94% gc time)


698-element Array{Array,1}:
 [48, 50]
 [16, 50]
 [50, 50]
 [50, 50]
 [50, 39]
 [7, 50] 
 [50, 50]
 [50, 50]
 [50, 50]
 [45, 50]
 [50, 50]
 [50, 50]
 [50, 50]
 ⋮       
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  

In [75]:
rwST = @time random_walk(multiplexST, 10, 5)

  0.540864 seconds (470.09 k allocations: 364.513 MiB, 8.33% gc time)


900-element Array{Any,1}:
 [35 147 … 617 840; 15 35 … 143 864; … ; 15 35 … 790 188; 15 1 … 14 95]       
 [11 133 … 95 154; 33 41 … 133 19; … ; 33 17 … 7 31; 33 161 … 188 92]         
 [164 506 … 73 466; 18 296 … 3 615; … ; 618 627 … 75 277; 203 549 … 134 117]  
 [35 168 … 26 37; 35 42 … 35 139; … ; 35 12 … 299 18; 35 177 … 73 146]        
 [35 40 … 187 3; 95 38 … 143 868; … ; 133 18 … 113 249; 28 38 … 397 380]      
 [35 34 … 249 267; 33 41 … 133 3; … ; 35 139 … 3 81; 35 133 … 175 133]        
 [22 18 … 18 97; 35 133 … 97 18; … ; 25 30 … 109 93; 31 18 … 324 469]         
 [286 294 … 42 18; 286 188 … 48 889; … ; 28 45 … 18 289; 286 188 … 73 108]    
 [95 45 … 0 0; 25 34 … 749 38; … ; 3 50 … 287 679; 18 301 … 176 137]          
 [161 198 … 313 531; 123 447 … 161 750; … ; 38 736 … 301 161; 34 95 … 95 118] 
 [133 3 … 3 611; 133 5 … 245 145; … ; 133 3 … 33 18; 133 18 … 21 3]           
 [3 274 … 130 369; 3 393 … 293 617; … ; 35 44 … 74 139; 95 380 … 73 85]       
 [28 9 … 18 28; 33 34 … 11

In [78]:
wlST = @time walk_length(rwST)

  0.042134 seconds (154.28 k allocations: 9.427 MiB)


900-element Array{Array,1}:
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [404, 0, 0, 0, 0] 
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 ⋮                 
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [1690, 0, 0, 0, 0]
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   
 [0, 0, 0, 0, 0]   

In [114]:
Min_length(rwOW)

1

In [94]:
?n_in_degree

search: n_in_degree



No documentation found.

`n_in_degree` is a `Function`.

```
# 1 method for generic function "n_in_degree":
[1] n_in_degree(M::Array{Int64,2}, n::Int64) in Main at In[93]:19
```


In [209]:
"""
n_in_degree(M, n)

Función que obtiene el grado de entrada de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de entrada del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_in_degree(M::Array{Int64,2}, n::Int64)
    grado_entrada = sum(M[n, :])
end

n_in_degree (generic function with 1 method)

In [210]:
"""
in_degree(M)

Función que obtiene el grado de entrada de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de entrada de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function in_degree(M::Array)
    grados_entrada = sum(M, dims = 2)
end

in_degree (generic function with 1 method)

In [217]:
"""
n_out_degree(M, n)

Función que obtiene el grado de salida de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de salida del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_out_degree(M::Array{Int64,2}, n::Int64)
    grado_salida = sum(M[:, n])
end

n_out_degree (generic function with 1 method)

In [218]:
"""
out_degree(M)

Función que obtiene el grado de salida de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de salida de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function out_degree(M::Array)
    grados_salida = sum(M, dims = 1)
end

out_degree (generic function with 1 method)

In [ ]:
in_degree(multiplex)

In [ ]:
out_degree(multiplex)

### Función r_walks

Caminatas aleatorias para un sólo nodo inicial.

In [156]:
"""
La función r_walks tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
f, nodo inicial de tipo Int64
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz, el cual tiene igual probabilidad de avanzar 
hacia cualquiera de sus vecinos.
Regresa un arreglo que contiene todas las trayectorias que tomó el caminante aleatorio.
"""

function r_walksP(M::Array{Int64,2}, f::Int64, steps::Int64, iter::Int64)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    #paths = zeros(Int64, (iter, steps + 1))
    #paths = [f]
    s = f
    #push!(paths, s)
    for i in 1:iter  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            if vecinos == []
                break
            else
                a = sample(vecinos)
                paths[i, p] = a
            s = a
            end
        end
        s = f
    end
    return paths 
end

r_walksP (generic function with 1 method)

In [2]:
function r_walks(M::Array{Int64,2}, f::Int64, steps::Int64, iter::Int64)
    nodos = size(M, 1) #aeropuertos  
    paths = zeros(Int64, (iter, steps + 1))
    s = f

    for i in 1:iter
        paths[i, 1] = f
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            if vecinos == []
                break
            else
                a = sample(vecinos)
                paths[i, p + 1] = a
            s = a
            end
        end
        s = f
    end
    return paths 
end

r_walks (generic function with 1 method)

#### Pruebas r_walks

r_walks(mmulti, 1, 10, 10)

In [5]:
d

UndefVarError: UndefVarError: d not defined

In [153]:
r_walksP(d, 1, 10, 3)

3×11 Array{Int64,2}:
 1  2  1  2  3  1  2  1  2  1  2
 1  2  3  1  2  3  1  2  1  2  3
 1  2  3  1  2  3  1  2  1  2  3

In [154]:
r_walks(d, 1, 10, 3)

3×10 Array{Int64,2}:
 2  3  1  2  3  1  2  3  1  2
 2  1  2  1  2  3  1  2  3  1
 2  3  1  2  3  1  2  1  2  3

In [145]:
d[3,1]

2

In [122]:
r_walks(multiplexOW,1, 10, 2)

2×10 Array{Int64,2}:
 61   5   61  1    2   82   46   73   2  145
 11  89  193  2  127  293  292  578  62  291

In [ ]:
@time r_walks(mmulti, 1, 10, 1)

In [ ]:
@time r_walks(mmulti, 1, 100, 1)

In [ ]:
@time r_walks(mmulti, 1, 100, 1)

In [ ]:
@time r_walks(mmulti, 1, 10, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 100, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 500, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 1000, 10)

In [ ]:
#Cambio el nodo inicial
@time r_walks(mmulti, 986, 1000, 10)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 100)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 1000)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 2000)

In [ ]:
#Más pasos
@time r_walks(mmulti, 1, 40, 500)

In [ ]:
#Más pasos
@time r_walks(mmulti, 1, 100, 500)

In [ ]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 1000)

In [ ]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 10000)

### Función random_walk

Llamaré a mi función que hace muchas iteraciones dentro de otra función que recorra todos mis nodos.

In [3]:
"""
La función random_walk tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz con igual probabilidad de avanzar 
hacia cualquiera de sus vecinos. Esta función recorre todos los nodos de la red como
nodos iniciales y sobre ellos itera para obtener el número de caminos que se le pidió.
Regresa un arreglo que contiene arreglos asociados a todas las trayectorias que tomó el 
caminante aleatorio para cada nodo inicial de la red.
"""

function random_walk(M::Array{Int64,2}, steps::Int64, iter::Int64) #Debo agregarle el nodo inicial al inicio del path
    random_walks = []
    nodos = size(M, 1)
    for f in 1:nodos #aeropuertos
        paths = r_walks(M, f, steps, iter)
        push!(random_walks, paths)
    end
    random_walks
end

random_walk (generic function with 1 method)

### Pruebas random_walk en el multiplex

In [169]:
pruebaOW = @time random_walk(multiplexOW, 50, 2)

  0.578884 seconds (666.85 k allocations: 422.394 MiB, 9.74% gc time)


698-element Array{Any,1}:
 [1 3 … 182 55; 1 85 … 61 152]      
 [2 35 … 20 46; 2 20 … 52 207]      
 [3 46 … 251 283; 3 10 … 0 0]       
 [4 177 … 644 261; 4 177 … 460 31]  
 [5 61 … 229 556; 5 61 … 0 0]       
 [6 46 … 46 198; 6 46 … 400 160]    
 [7 46 … 127 301; 7 177 … 0 0]      
 [8 120 … 327 306; 8 120 … 92 200]  
 [9 178 … 271 52; 9 178 … 25 97]    
 [10 364 … 245 61; 10 3 … 193 89]   
 [11 89 … 141 271; 11 1 … 168 172]  
 [12 62 … 265 127; 12 127 … 356 314]
 [13 2 … 1 61; 13 127 … 0 0]        
 ⋮                                  
 [687 0 … 0 0; 687 0 … 0 0]         
 [688 0 … 0 0; 688 0 … 0 0]         
 [689 0 … 0 0; 689 0 … 0 0]         
 [690 0 … 0 0; 690 0 … 0 0]         
 [691 0 … 0 0; 691 0 … 0 0]         
 [692 0 … 0 0; 692 0 … 0 0]         
 [693 0 … 0 0; 693 0 … 0 0]         
 [694 0 … 0 0; 694 0 … 0 0]         
 [695 0 … 0 0; 695 0 … 0 0]         
 [696 0 … 0 0; 696 0 … 0 0]         
 [697 0 … 0 0; 697 0 … 0 0]         
 [698 0 … 0 0; 698 0 … 0 0]         

In [ ]:
#5 iteraciones de un caminante aleatorio de 100 pasos sobre todos los nodos del multiplex 
@time random_walk(multiplex, 100, 5)

In [ ]:
#2 iteraciones de un caminante aleatorio de 50 pasos sobre todos los nodos del multiplex 
prueba = @time random_walk(multiplex, 100, 2)

In [ ]:
#2 Caminatas de 100 pasos para nodo inicial 1
prueba[1]

In [ ]:
#2 Caminatas de 100 pasos para nodo inicial 3160
prueba[3160]

In [ ]:
length(prueba)

In [ ]:
size(prueba)

In [ ]:
length(prueba[2])

In [ ]:
s = size(prueba[3160])

In [ ]:
s[1]

In [ ]:
length(prueba[3160])

In [ ]:
#Tomo el renglón 2 del arreglo de 2 iteraciones de 50 pasos del nodo inicial 3160
prueba1[3160][2, :]

In [ ]:
prueba1[3160][2, :][5]

### Función que cuenta longitud de cada iteración de la caminata antes de llegar a un cero

In [110]:
"""
La función walk_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función random_walk). Regresa un arreglo de arreglos, en donde cada entrada corresponde a la longitud de 
la caminata aleatoria antes de caer en un nodo con grado de salida 0.
"""

function walk_lengthP(W)
    
    longitudes = Array[]
    c = 0
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v
        #@show i
        for j in 1:s
            #@show j
            for k in 1:t
                #@show k
                
                if W[i][j, :][k] != 0 #W[i][j, :] #renglón a analizar
                    c += 1 
                    #@show c
                else
                    #@show c
                    longz[j] = c 
                    #@show long #ant[i][j] = W[i][j, :][k - 1]
                    c = 0
                    break
                end
                #@show longz[j]
            end
            @show longz[j]
            
        end
        push!(longitudes, longz)
        #@show longitudes
        longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    end
    return longitudes
end

walk_length (generic function with 1 method)

In [173]:
function walk_length(W)
    
    longitudes = Array[]
    c = 0
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v
        #@show i
        for j in 1:s
            #@show j
            for k in 1:t
                #@show k
                
                if W[i][j, :][k] != 0 #W[i][j, :] #renglón a analizar
                    c += 1 
                else
                    break
                    
                    #@show c
                    
                    #@show long #ant[i][j] = W[i][j, :][k - 1]
                    
                end
                
            end
            longz[j] = c - 1
            #@show longz[j]
            c = 0
            
        end
        push!(longitudes, longz)
        #@show longitudes
        longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    end
    return longitudes
end

walk_length (generic function with 1 method)

In [12]:
d = [0  1  0
     1  0  1
     0  0  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  0  0

In [51]:
#2 iteraciones de un caminante aleatorio de 10 pasos sobre todos los nodos del multiplex 
pruebad = @time random_walk(d, 10, 2)

  0.000017 seconds (157 allocations: 9.297 KiB)


3-element Array{Any,1}:
 [2 3 … 0 0; 2 1 … 0 0]
 [1 2 … 0 0; 1 2 … 0 0]
 [0 0 … 0 0; 0 0 … 0 0]

In [52]:
pruebad[1]

2×10 Array{Int64,2}:
 2  3  0  0  0  0  0  0  0  0
 2  1  2  3  0  0  0  0  0  0

In [53]:
pruebad[2]

2×10 Array{Int64,2}:
 1  2  1  2  3  0  0  0  0  0
 1  2  3  0  0  0  0  0  0  0

In [54]:
pruebad[3]

2×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [55]:
prueba_lengthd = @time walk_length(pruebad)

  0.000077 seconds (85 allocations: 5.188 KiB)


3-element Array{Array,1}:
 [2, 4]
 [5, 3]
 [0, 0]

In [56]:
walk_length(pruebad)

3-element Array{Array,1}:
 [2, 4]
 [5, 3]
 [0, 0]

In [174]:
walk_length(pruebaOW)

698-element Array{Array,1}:
 [50, 50]
 [50, 50]
 [50, 9] 
 [50, 50]
 [50, 8] 
 [50, 50]
 [50, 17]
 [50, 50]
 [50, 50]
 [50, 50]
 [50, 50]
 [50, 50]
 [50, 6] 
 ⋮       
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  
 [0, 0]  

### Función que obtiene el promedio de la longitud de la caminata por nodo antes de llegar a un cero

In [59]:
"""
La función walk_av_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función walk_length). 
Regresa un arreglo con entradas correspondientes al promedio de las longitudes de 
las caminatas aleatorias para cada nodo de inicio antes de caer en un nodo con grado de salida 0.
"""

function walk_av_length(W) #Llamar a función
    
    proms = []
    wlength = walk_length(W)
    
    for i in 1:length(wlength)
        av = mean(wlength[i])
        push!(proms, av)
    end
    proms
end

walk_av_length (generic function with 1 method)

In [60]:
walk_av_length(pruebad)

3-element Array{Any,1}:
 3.0
 4.0
 0.0

### Función que da los nodos diferentes en cada iteración de cada caminata antes de llegar a un cero

In [61]:
"""
La función n_cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa los nodos diferentes a los que llega el caminante.
"""

function n_cobertura(W)
    
    cobert = []
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    #visit = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    visit = []
    
    for i in 1:v        
        for j in 1:s
            u = unique(W[i][j, :])
            push!(visit, u)
        end
        push!(cobert, visit)
        visit = []
    end
    return cobert
end

n_cobertura (generic function with 1 method)

In [62]:
cob = n_cobertura(pruebad)

3-element Array{Any,1}:
 Any[[2, 3, 0], [2, 1, 3, 0]]   
 Any[[1, 2, 3, 0], [1, 2, 3, 0]]
 Any[[0], [0]]                  

In [65]:
cob[1][2]

4-element Array{Int64,1}:
 2
 1
 3
 0

### Función que da el número de nodos diferentes, cobertura dado n_cobertura

In [67]:
"""
La función cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa el número de nodos diferentes a los que llega el caminante.
"""

#Tal vez falta llamar dentro de la función a la función n_cobertura

function cobertura(W) 
    
    cobert = []
    
    v = length(W) #tamaño de la matriz, número de nodos
    x = n_cobertura(W)
    s = size(x[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v        
        for j in 1:s
            l = length(x[i][j])
            longz[j] = l
        end
        push!(cobert, longz)
        longz = zeros(Int64, s)
    end
    return cobert
end

cobertura (generic function with 1 method)

In [68]:
cobertura(pruebad) #No sirve si le damos el random walk

3-element Array{Any,1}:
 [3, 4]
 [4, 4]
 [1, 1]

In [ ]:
cobertd = cobertura(cob) #Sí sirve si le damos n_cobertura

### Función que saca el promedio de las longitudes de (las iteraciones de) cada nodo

In [69]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function n_length_av(W) #Esta es la importante
    
    longitud = []
    x = cobertura(W)
    
    for i in 1:length(x)
        l = mean(x[i])
        push!(longitud, l)
    end
    longitud
end

n_length_av (generic function with 1 method)

In [70]:
n_cobertd = n_length_av(pruebad)

3-element Array{Any,1}:
 3.5
 4.0
 1.0

### Función que obtiene el promedio de las longitudes promedio. Promedio general.

In [71]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura y n_length_av

function length_av(W)
    x = n_length_av(W)
    promedio = mean(x)
    return promedio

end

length_av (generic function with 1 method)

In [72]:
length_av(pruebad)

2.8333333333333335

### Función que obtiene el máximo de las longitudes de la función cobertura

In [74]:
"""

"""


function max_length(W)
    max = []
    x = cobertura(W)
    for i in 1:length(x)
        m = maximum(x[i])
        push!(max, m)
    end
    max
end

max_length (generic function with 1 method)

In [76]:
maxd = max_length(pruebad)

3-element Array{Any,1}:
 4
 4
 1

### Función que obtiene el máximo de los máximos

In [77]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function Max_length(W)
    x = max_length(W)
    m = maximum(x)
    return m
end

Max_length (generic function with 1 method)

In [78]:
Max_length(pruebad)

4

### Función que obtiene el promedio del máximo de las longitudes de la función cobertura

In [79]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function av_max_length(W)
    x = max_length(W)
    prom = mean(x)
    return prom
end

av_max_length (generic function with 1 method)

In [80]:
av_max_length(pruebad)

3.0

### Función que obtiene el mínimo de las longitudes de la función cobertura

In [81]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function min_length(W)
    min = []
    x = cobertura(W)
    for i in 1:length(x)
        m = minimum(x[i])
        push!(min, m)
    end
    min
end

min_length (generic function with 1 method)

In [82]:
mind = min_length(pruebad)

3-element Array{Any,1}:
 3
 4
 1

### Función que obtiene el mínimo de los mínimos

In [84]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function Min_length(W)
    x = min_length(W)
    m = minimum(x)
    return m
end

Min_length (generic function with 1 method)

In [85]:
Min_length(pruebad)

1

### Función que obtiene el promedio del mínimo de las longitudes de la función cobertura

In [86]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function av_min_length(W)
    x = min_length(W)
    prom = mean(x)
    return prom
end

av_min_length (generic function with 1 method)

In [87]:
av_min_length(pruebad)

2.6666666666666665

### Función que obtiene el nodo más cercano al cero de las caminatas

In [10]:
d

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  0  0

In [15]:
w = random_walk(d, 5, 2)

3-element Array{Any,1}:
 [1 2 … 1 2; 1 2 … 1 2]
 [2 1 … 2 3; 2 3 … 0 0]
 [3 0 … 0 0; 3 0 … 0 0]

In [24]:
w[2]

2×6 Array{Int64,2}:
 2  1  2  1  2  3
 2  3  0  0  0  0

In [17]:
d[2,:][end]

1

In [23]:
size(w[1],2)

6

In [ ]:
for i in 1:length(w)
    for j in 1:length(size(w[i],1))
        for k in 1:length(size(w[i],2))
            if w[i][j,:][k] != 0

In [183]:
d[length(y)-1]

4

In [185]:
y[end]

0

In [ ]:
function atractor(W) #Debo llamar a walks
   atractores = []
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    #visit = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    visit = []
    
    for i in 1:v        
        for j in 1:s
            if 
            a = W[i][j, :])
            push!(visit, u)
        end
        push!(cobert, visit)
        visit = []
    end
    return cobert
end

In [ ]:
function atractores(W)
    x = n_cobertura(W)
    at = []
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(x[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v
        for j in 1:s
            
        
    end
end


cobert = []
    
    v = length(W) #tamaño de la matriz, número de nodos
    x = n_cobertura(W)
    s = size(x[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    longz = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v        
        for j in 1:s
            l = length(x[i][j])
            longz[j] = l
        end
        push!(cobert, longz)
        longz = zeros(Int64, s)
    end
    return cobert

### Función que obtiene la mediana de cobertura

In [ ]:
"""

"""
#No sirve
#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function med_length(W)
    med = []
    for i in 1:length(W)
        m = StatsBase.median(W)
        push!(med, m)
    end
    med
end

In [ ]:
med_length(cobertd)

In [ ]:
StatsBase.median(1.0, 3, 5, a)

In [ ]:
cobertd

#### Pruebas random_walk

In [ ]:
@time random_walk(mmulti, 10, 1)

In [ ]:
#10 pasos, 10 iteraciones
@time random_walk(mmulti, 10, 10)

In [ ]:
#50 pasos, 1 iteración
@time random_walk(mmulti, 50, 1)

In [ ]:
#50 pasos, 10 iteraciones
@time random_walk(mmulti, 50, 10)

In [ ]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 50)

In [ ]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 100)

### Redes artificiales

#### Ciclo

In [ ]:
c1 = [0  1  0  0  1
      1  0  1  0  0
      0  1  0  1  0
      0  0  1  0  1
      1  0  0  1  0]

In [ ]:
rc1 = @time random_walk(c1, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 1 
rc1[1]

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 2
rc1[2]

#### 2 ciclos

In [ ]:
c2 = [0  1  1  0  0  0  
      1  0  1  0  0  0
      1  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  1
      0  0  0  0  1  1]

In [ ]:
rc2 = @time random_walk(c2, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 1 de una red de 2 ciclos
rc2[1]

In [ ]:
rc2[5]

#### Eg2

In [ ]:
t1 = [0  1  0  
      1  0  1 
      0  1  0]

In [ ]:
rt1 = @time random_walk(t1, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos
rt1[1]

In [ ]:
t2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  0
      0  0  0  1  0  0]

In [ ]:
rt2 = @time random_walk(t2, 100, 10)

In [ ]:
#Nodo inicial 2
rt2[2]

In [ ]:
rt2[6]

### Lineal

In [ ]:
l1 = [0  1  0  0  
      1  0  1  0
      0  1  0  1
      0  0  1  0]

In [ ]:
rl1 = @time random_walk(l1, 100, 10)

In [ ]:
rl1[1]

In [ ]:
rl1[4]

### 2 Lineal

In [ ]:
l2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  0
      0  0  0  1  0  1
      0  0  0  0  1  0]

In [ ]:
rl2 = @time random_walk(l2, 100, 10)

In [ ]:
rl2[3]

In [ ]:
rl2[5]

### Clica

In [ ]:
g1 = [0  1  1  1  
      1  0  1  1
      1  1  0  1
      1  1  1  0]

In [ ]:
rg1 = @time random_walk(g1, 100, 10)

In [ ]:
rg1[1]

### 2 Clicas

In [ ]:
g2 = [0  1  1  1  0  0  0  0  
      1  0  1  1  0  0  0  0
      1  1  0  1  0  0  0  0
      1  1  1  0  0  0  0  0
      0  0  0  0  0  1  1  1
      0  0  0  0  1  0  1  1
      0  0  0  0  1  1  0  1
      0  0  0  0  1  1  1  0]

In [ ]:
rg2 = @time random_walk(g2, 100, 10)

In [ ]:
rg2[7]

### Grafo dirigido

In [ ]:
gd = [0  1  1  1  
      0  0  1  1
      0  1  0  0
      0  0  0  0]

In [ ]:
rgd = @time random_walk(gd, 100, 10)

In [ ]:
rgd[1]

In [ ]:
rgd[2]

In [ ]:
rgd[3]

In [ ]:
rgd[4]

In [ ]:
in_degree(gd)

In [ ]:
uhu = random_walk_f(c, 3, 2)

In [ ]:
uhu[1]

In [ ]:
#Ejemplo grande
eg = random_walk_f(c, 1000, 1000)

In [ ]:
eg[3]

In [192]:
tablita = CSV.read("data/multi_OW_du.csv"; header = true, datacol = 2, types=Dict("col1"=>String))

698×699 DataFrame. Omitted printing of 691 columns
│ Row │ Column1 │ EZE    │ MIA    │ PUJ    │ ABE    │ ABQ    │ AGS    │ ALB    │
│     │ String⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │
├─────┼─────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1   │ EZE     │ 0      │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │
│ 2   │ MIA     │ 1      │ 0      │ 1      │ 0      │ 0      │ 0      │ 0      │
│ 3   │ PUJ     │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 4   │ ABE     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 5   │ ABQ     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 6   │ AGS     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 7   │ ALB     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 8   │ AMS     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 9   │ ANC     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 10  │ ANU     │ 0      │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │
⋮
│ 688 │ LEX     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 689 │ MOB     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 690 │ PWM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 691 │ TYS     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 692 │ VPS     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 693 │ KEM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 694 │ AAL     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 695 │ SLA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 696 │ TUC     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 697 │ IQT     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 698 │ NJC     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │

In [193]:
typeof(tablita)

DataFrame

In [199]:
nom_tabli = names(tablita)

699-element Array{Symbol,1}:
 :Column1
 :EZE    
 :MIA    
 :PUJ    
 :ABE    
 :ABQ    
 :AGS    
 :ALB    
 :AMS    
 :ANC    
 :ANU    
 :ASU    
 :ATH    
 ⋮       
 :CRW    
 :LEX    
 :MOB    
 :PWM    
 :TYS    
 :VPS    
 :KEM    
 :AAL    
 :SLA    
 :TUC    
 :IQT    
 :NJC    

In [196]:
tablita[2,1]

"MIA"

In [197]:
tabli = tablita[:, 2:end]

698×698 DataFrame. Omitted printing of 690 columns
│ Row │ EZE    │ MIA    │ PUJ    │ ABE    │ ABQ    │ AGS    │ ALB    │ AMS    │
│     │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │
├─────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1   │ 0      │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 2   │ 1      │ 0      │ 1      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3   │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 4   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 5   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 6   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 7   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 8   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 9   │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 10  │ 0      │ 1      │ 1      │ 0      │ 0      │ 0      │ 0      │ 0      │
⋮
│ 688 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 689 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 690 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 691 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 692 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 693 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 694 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 695 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 696 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 697 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 698 │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │

In [221]:
tabli[1] #primer renglón del dataframe

698-element Array{Union{Missing, Int64},1}:
 0
 1
 1
 0
 0
 0
 0
 0
 0
 0
 1
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [202]:
nom_tabli[2]

:EZE

In [204]:
rwOW[1]

2×50 Array{Int64,2}:
 89  465   89  31  454   31  436  31  …  164   61  210   46  692    0    0
 85  193  222  31   85  433  448  31     613  292  358  292  329  292  324

In [205]:
nom_tabli[692]

:TYS

In [212]:
in_degree(tabli)

MethodError: MethodError: no method matching in_degree(::DataFrame)
Closest candidates are:
  in_degree(!Matched::Array) at In[210]:18

In [213]:
in_degree(multiplexOW)

698×1 Array{Int64,2}:
 11
 96
  6
  1
  1
  1
  2
  7
  1
  7
  3
  5
  4
  ⋮
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0

In [214]:
n_in_degree(multiplexOW, 692)

0

In [216]:
n_in_degree(multiplexOW, 2)

96

In [219]:
out_degree(multiplexOW)

1×698 Array{Int64,2}:
 11  96  6  1  1  1  2  7  1  7  3  5  …  1  1  1  2  1  1  1  1  1  1  1  1

In [220]:
n_out_degree(multiplexOW, 692)

1

In [225]:
unique(tabli[692])

2-element Array{Union{Missing, Int64},1}:
 0
 1

In [235]:
reng = multiplexOW[692,:]

698-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [236]:
unique(reng)

1-element Array{Int64,1}:
 0

In [233]:
colu = multiplexOW[:, 692]

698-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [234]:
unique(hola2)

2-element Array{Int64,1}:
 0
 1

In [ ]:
CSV.validate("data/matriz_multi_uw.csv"; header = true)

In [ ]:
#Por lo pronto probamos con este

random_walk_f(mmulti, 150, 1000)

In [ ]:
mmulti[7, :][594]

In [ ]:
#Checamos si encuentra los vecinos correctamente
findall(x -> x != 0, mmulti[1899, :])

In [ ]:
findall(x -> x != 0, mmulti[1000, :]) == []

In [ ]:
size(mmulti, 1)

In [ ]:
#Por lo pronto probamos con este


random_walk_f(mmulti, 10, 2)

In [ ]:
#Matriz fea
d = [0  1  0
     1  0  1
     0  0  0]  

In [ ]:
d

In [ ]:
random_walk_modif(d, 2, 5, 4)

In [ ]:
    rw = []
    #nodos = size(M, 1)
    for f in 1:size(mmulti, 1) #aeropuertos
        p = random_walk_modif(mmulti, f, 3, 3)
        push!(rw, p)
    end
    rw

In [ ]:
rw[2000]

In [ ]:
random_walk_f(mmulti, 5, 2)

In [ ]:
readdlm("data/matriz_multi_uw.csv", ',', header = true)

In [ ]:
?readdlm;

In [ ]:
?NamedArrays.setnames!

In [ ]:
colu = ["a", "b", "c"]
reng = ["hola", "hi", "hey"]

In [ ]:
xx = NamedArray(c, ["hola", "hi", "hey"])

In [ ]:
setnames!(a::NamedArray, names::Vector, dim::Int)

# NamedArray{T,N}(a::Array{T,N}, names::NTuple{N,Vector}, dimnames::NTuple{N})
x = NamedArray(Int[1 3; 2 4], ( ["A","B"], ["C","D"] ), ("ROWS","COLS"))

n = NamedArray(rand(2,4))
setnames!(n, ["one", "two"], 1)         # give the names "one" and "two" to the rows (dimension 1)

In [ ]:
function random_walkM3(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    @show nodos
    paths = zeros(Int64, (nodos*iter, steps)) 
    @show paths
    for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos 
        @show s
        m = s
        @show m
        for i = 1:iter
            @show i
            for p in 1:steps 
                @show p
                row = M[m, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                @show paths
                m = a
                @show m
            end
            m = s
            @show m
        end
    end
    paths
end

In [ ]:
function random_walk(M, steps)
    nodos = size(M, 1)
    paths = zeros(steps)
    for s in 1:nodos
        row = M[s, :]
        n_vecinos = sum(row)
        proba = 1/n_vecinos
        proba1 = 1/(n_vecinos - 1)
        p = rand()
        for i in 1:n_vecinos
            if proba< p <
        if 0 proba1 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

In [ ]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walk1d(n) #Función de caminante aleatorio en 1 dim.
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walkM(M, steps) #, iter)
    nodos = size(M, 1) #aeropuertos
    path = zeros(steps) 
    for i = 1 #for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos  
        @show i
        for p in 1:steps 
            @show p
            row = M[i, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            @show vecinos
            a = sample(vecinos)
            @show a
            path[p] = a
            i = a
        end
    end
    path
end

In [ ]:
function random_walkM2(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    for s = 1 #nodo inicial
        @show s
        for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
            @show i
            for p in 1:steps 
                #@show p
                row = M[s, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                s = a
            end
            s = 1
            @show paths
        end
    end
    return paths
end

In [ ]:
#Función 
function random_walk2(M, f, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            a = sample(vecinos)
            paths[i, p] = a
            s = a
        end
        s = f
    end
    return paths 
end

In [ ]:
#Eg. función
#b = random_walk2(c, 1, 50, 100)
k = random_walk2(c, 1, 10, 10)