# Random Walks en Redes Multicapa de Aerolíneas

In [ ]:
using Pkg

In [ ]:
Pkg.add("StatsBase")

In [10]:
using StatsBase

In [172]:
using DelimitedFiles

In [8]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 1  1  0

In [ ]:
?dim

In [ ]:
zeros(Int, size(c))

In [ ]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

In [1]:
function rw1d(n) #NO
    path = zeros(n)
    for i in 1:n
        if rand()<= 1/2
            path[i] += 1
        else
            path[i] -= 1
        end
    end  
    path   
end

rw1d (generic function with 1 method)

In [2]:
rw1d(6)

6-element Array{Float64,1}:
  1.0
  1.0
  1.0
 -1.0
 -1.0
  1.0

In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
z = random_walk1d(5)

In [ ]:
z = [0, 1, 1, 0, 1]

In [ ]:
h = 1:10

In [ ]:
sample(h)

In [ ]:
?sample

In [3]:
function random_walk1d(n) #Función de caminante aleatorio en 1 dim.
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

random_walk1d (generic function with 1 method)

In [6]:
random_walk1d(4)

lugar = 1
lugar = 2
lugar = 1
lugar = 0


5-element Array{Float64,1}:
 0.0
 1.0
 2.0
 1.0
 0.0

In [35]:
function random_walkM(M, steps) #, iter)
    nodos = size(M, 1) #aeropuertos
    path = zeros(steps) 
    for i = 1 #for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos  
        @show i
        for p in 1:steps 
            @show p
            row = M[i, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            @show vecinos
            a = sample(vecinos)
            @show a
            path[p] = a
            i = a
        end
    end
    path
end

random_walkM (generic function with 1 method)

In [36]:
random_walkM(c, 3)

i = 1
p = 1
vecinos = [2]
a = 2
p = 2
vecinos = [1, 3]
a = 3
p = 3
vecinos = [1, 2]
a = 1


3-element Array{Float64,1}:
 2.0
 3.0
 1.0

In [40]:
paths = zeros(Int64, (2, 5))

2×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0

In [42]:
paths[2] = 2
paths

2×5 Array{Int64,2}:
 0  0  0  0  0
 2  0  0  0  0

In [43]:
paths[3] = 3
paths

2×5 Array{Int64,2}:
 0  3  0  0  0
 2  0  0  0  0

In [46]:
paths[2,4] = 10
paths

2×5 Array{Int64,2}:
 0  3  0   0  0
 2  0  0  10  0

Pruebas función RWM

In [118]:
function random_walkM2(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    for s = 1 #nodo inicial
        @show s
        for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
            @show i
            for p in 1:steps 
                #@show p
                row = M[s, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                s = a
            end
            s = 1
            @show paths
        end
    end
    return paths
end

random_walkM2 (generic function with 1 method)

In [119]:
random_walkM2(c, 3, 2)

s = 1
i = 1
vecinos = [2]
a = 2
vecinos = [1, 3]
a = 1
vecinos = [2]
a = 2
paths = [2 1 2; 0 0 0]
i = 2
vecinos = [2]
a = 2
vecinos = [1, 3]
a = 3
vecinos = [1, 2]
a = 2
paths = [2 1 2; 2 3 2]


2×3 Array{Int64,2}:
 2  1  2
 2  3  2

In [143]:
function random_walk2(M, f, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
        for p in 1:steps 
            #@show p
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            a = sample(vecinos)
            paths[i, p] = a
            s = a
        end
        s = f
    end
    return paths
end

random_walk2 (generic function with 2 methods)

Llamaré a mi función que hace muchas iteraciones dentro de otra función que recorra todos mis nodos.

In [144]:
function random_walk_f(M, f, steps, iter)
    #nodos = size(M, 1) #aeropuertos

        random_walk2(M, f, steps, iter)
    
end

random_walk_f (generic function with 2 methods)

In [145]:
random_walk_f(c, 2, 3, 2)

2×3 Array{Int64,2}:
 3  2  1
 1  2  3

In [154]:
#Ejemplo grande
random_walk_f(c, 2, 1000, 1000)

1000×1000 Array{Int64,2}:
 1  2  3  2  1  2  3  2  1  2  1  2  1  …  1  2  3  1  2  3  2  1  2  1  2  1
 1  2  3  1  2  3  1  2  3  1  2  3  1     2  3  1  2  1  2  1  2  3  1  2  3
 1  2  1  2  1  2  3  2  3  2  3  1  2     2  1  2  1  2  3  2  1  2  1  2  3
 1  2  1  2  1  2  1  2  3  1  2  3  1     2  3  1  2  3  2  1  2  1  2  3  1
 3  1  2  1  2  1  2  1  2  3  2  1  2     2  3  2  3  2  1  2  3  2  1  2  1
 3  2  3  1  2  3  1  2  1  2  3  2  1  …  2  3  2  1  2  1  2  3  2  1  2  1
 3  2  3  1  2  3  1  2  1  2  3  1  2     2  1  2  3  2  3  2  1  2  3  2  3
 1  2  3  1  2  1  2  3  1  2  3  1  2     1  2  3  1  2  1  2  1  2  1  2  1
 3  1  2  1  2  3  2  3  1  2  3  1  2     3  2  1  2  1  2  1  2  3  1  2  1
 1  2  3  2  1  2  1  2  1  2  3  2  1     2  3  1  2  1  2  1  2  3  1  2  1
 3  2  1  2  1  2  1  2  3  1  2  1  2  …  2  1  2  3  1  2  3  1  2  1  2  1
 1  2  1  2  3  1  2  1  2  3  1  2  1     2  1  2  1  2  3  2  3  1  2  3  2
 1  2  1  2  1  2  1  2  1  2  1  2  3

In [155]:
using CSV

In [180]:
CSV.read("data/matriz_multi_uw.csv"; header = true, datacol = 2, types=Dict("col1"=>String))

3045×3046 DataFrames.DataFrame. Omitted printing of 3039 columns
│ Row  │ Column1 │ BCM    │ CLJ    │ FCO    │ IAS    │ LCA    │ OTP    │
│      │ String⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │
├──────┼─────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1    │ BCM     │ 0      │ 0      │ 1      │ 0      │ 0      │ 0      │
│ 2    │ CLJ     │ 0      │ 0      │ 0      │ 0      │ 1      │ 1      │
│ 3    │ FCO     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 4    │ IAS     │ 0      │ 1      │ 1      │ 0      │ 1      │ 0      │
│ 5    │ LCA     │ 0      │ 0      │ 1      │ 0      │ 0      │ 0      │
│ 6    │ OTP     │ 1      │ 1      │ 1      │ 1      │ 1      │ 0      │
│ 7    │ SBZ     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 8    │ TRN     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 9    │ TIA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 10   │ LIM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
⋮
│ 3035 │ OOM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3036 │ MYA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3037 │ KRB     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3038 │ CVQ     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3039 │ EPR     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3040 │ MJK     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3041 │ HGD     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3042 │ ARM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3043 │ OAG     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3044 │ CTL     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3045 │ LRE     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │

In [178]:
CSV.validate("data/matriz_multi_uw.csv"; header = true)

In [176]:
readdlm("data/matriz_multi_uw.csv", ',')

3046×3046 Array{Any,2}:
 ""      "BCM"   "CLJ"   "FCO"   "IAS"  …   "ARM"   "OAG"   "CTL"   "LRE"
 "BCM"  0       0       1       0          0       0       0       0     
 "CLJ"  0       0       0       0          0       0       0       0     
 "FCO"  0       0       0       0          0       0       0       0     
 "IAS"  0       1       1       0          0       0       0       0     
 "LCA"  0       0       1       0       …  0       0       0       0     
 "OTP"  1       1       1       1          0       0       0       0     
 "SBZ"  0       0       0       0          0       0       0       0     
 "TRN"  0       0       0       0          0       0       0       0     
 "TIA"  0       0       0       0          0       0       0       0     
 "LIM"  0       0       0       0       …  0       0       0       0     
 "ACC"  0       0       0       0          0       0       0       0     
 "BOY"  0       0       0       0          0       0       0       0     
 ⋮            

In [177]:
readdlm("data/matriz_multi_uw.csv", ',', header = true)

(Any["BCM" 0 … 0 0; "CLJ" 0 … 0 0; … ; "CTL" 0 … 0 0; "LRE" 0 … 0 0], AbstractString["" "BCM" … "CTL" "LRE"])

In [175]:
?readdlm

search: readdlm readdir



```
readdlm(source, T::Type; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt", Int64)
4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8

julia> readdlm("delim_file.txt", Float64)
4×2 Array{Float64,2}:
 1.0  5.0
 2.0  6.0
 3.0  7.0
 4.0  8.0

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, T::Type; options...)
```

The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',', Float64)
4×2 Array{Float64,2}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")
```

---

```
readdlm(source; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt")
4×2 Array{Any,2}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar; options...)
```

The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Array{Float64,2}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")

julia> z = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x z], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Array{Any,2}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, eol::AbstractChar; options...)
```

If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

---

```
readdlm(source, delim::AbstractChar, T::Type, eol::AbstractChar; header=false, skipstart=0, skipblanks=true, use_mmap, quotes=true, dims, comments=false, comment_char='#')
```

Read a matrix from the source where each line (separated by `eol`) gives one row, with elements separated by the given delimiter. The source can be a text file, stream or byte array. Memory mapped files can be used by passing the byte array representation of the mapped segment as source.

If `T` is a numeric type, the result is an array of that type, with any non-numeric elements as `NaN` for floating-point types, or zero. Other useful values of `T` include `String`, `AbstractString`, and `Any`.

If `header` is `true`, the first row of data will be read as header and the tuple `(data_cells, header_cells)` is returned instead of only `data_cells`.

Specifying `skipstart` will ignore the corresponding number of initial lines from the input.

If `skipblanks` is `true`, blank lines in the input will be ignored.

If `use_mmap` is `true`, the file specified by `source` is memory mapped for potential speedups. Default is `true` except on Windows. On Windows, you may want to specify `true` if the file is large, and is only read once and not written to.

If `quotes` is `true`, columns enclosed within double-quote (") characters are allowed to contain new lines and column delimiters. Double-quote characters within a quoted field must be escaped with another double-quote.  Specifying `dims` as a tuple of the expected rows and columns (including header, if any) may speed up reading of large files.  If `comments` is `true`, lines beginning with `comment_char` and text following `comment_char` in any line are ignored.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end

julia> readdlm("delim_file.txt", '\t', Int, '\n')
4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8
```


In [157]:
pwd()

"/Users/Yuriko/Documents/UNAM/Tesis_Lic/Code"

In [158]:
homedir()

"/Users/yuriko"

In [164]:
cd("$(homedir())/Documents/UNAM/Tesis_Lic")

In [165]:
pwd()

"/Users/Yuriko/Documents/UNAM/Tesis_Lic"

In [108]:
function random_walkM3(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    @show nodos
    paths = zeros(Int64, (nodos*iter, steps)) 
    @show paths
    for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos 
        @show s
        m = s
        @show m
        for i = 1:iter
            @show i
            for p in 1:steps 
                @show p
                row = M[m, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                @show paths
                m = a
                @show m
            end
            m = s
            @show m
        end
    end
    paths
end

random_walkM3 (generic function with 1 method)

In [ ]:
function random_walk(M, steps)
    nodos = size(M, 1)
    paths = zeros(steps)
    for s in 1:nodos
        row = M[s, :]
        n_vecinos = sum(row)
        proba = 1/n_vecinos
        proba1 = 1/(n_vecinos - 1)
        p = rand()
        for i in 1:n_vecinos
            if proba< p <
        if 0 proba1 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

In [ ]:
x = rand() 
x

In [ ]:
v = (0.7,0.9)

In [ ]:
x
if x < 0.7
    println("false")
    elseif 0.7 < x < 0.9
        println("true")
    else 0.9 < x
        println("false")
end

In [ ]:
x

In [ ]:
?is

In [ ]:
multiplex(a, b, c)

In [ ]:
c = [0  1  0
 1  0  1
 0  1  0]

In [ ]:
findall(1, c)

In [ ]:
# Buscamos vecinos

n0 = 1 # nodo inicial
vecinos = A[n_0, :]
p = 1/length(vecinos) # probabilidad


In [ ]:
using CSV

In [ ]:
CSV.read("/Users/yuriko/Documents/UNAM/Tesis_Lic/m_multiplex.csv"; delim = ("""))

In [ ]:
?CSV.read

In [ ]:
CSV.read("/Users/yuriko/Documents/UNAM/Tesis_Lic/m_multiplex_df.csv")