# Random Walks en Redes Multicapa de Aerolíneas

In [1]:
using StatsBase

In [2]:
using DelimitedFiles

In [3]:
using NamedArrays

In [4]:
using CSV

In [5]:
using LightGraphs

In [6]:
cd("$(homedir())/Documents/UNAM/Tesis_Lic")

In [7]:
pwd()

"/Users/Yuriko/Documents/UNAM/Tesis_Lic"

In [ ]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

d = [0  1  0
     1  0  1
     0  0  0];

In [8]:
multiplex17 = readdlm("data/matriz_multiplex_du.csv", ',')

3190×3190 Array{Any,2}:
 ""      "AER"   "ASF"   "CEK"   "DME"  …   "BSS"   "AEX"   "GCK"   "MGM"
 "AER"  0       0       0       1          0       0       0       0     
 "ASF"  0       0       0       1          0       0       0       0     
 "CEK"  0       0       0       1          0       0       0       0     
 "DME"  1       1       1       0          0       0       0       0     
 "EGO"  0       0       0       1       …  0       0       0       0     
 "GYD"  0       0       0       1          0       0       0       0     
 "KGD"  0       0       0       1          0       0       0       0     
 "KZN"  1       1       1       1          0       0       0       0     
 "LED"  1       1       1       1          0       0       0       0     
 "MRV"  0       1       0       1       …  0       0       0       0     
 "NBC"  0       0       0       1          0       0       0       0     
 "NJC"  0       0       0       1          0       0       0       0     
 ⋮            

In [9]:
multiplex17 = multiplex17[2:end, :];

In [10]:
multiplex17 = multiplex17[:, 2:end];

In [11]:
multiplex = convert(Array{Int64,2}, multiplex17)

3189×3189 Array{Int64,2}:
 0  0  0  1  0  0  0  1  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  1  1  1  1  1  1  1  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  1  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  1  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  0  1  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  1  0  0  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0

In [17]:
in_degree(multiplex)

3189×1 Array{Int64,2}:
  17
   7
  14
 187
   9
  39
  10
  21
 110
  16
   7
   9
  10
   ⋮
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0

In [18]:
out_degree(multiplex)

1×3189 Array{Int64,2}:
 18  7  14  186  9  39  10  21  112  …  1  3  1  1  1  1  1  1  1  1  1  1

### Función r_walks

Caminatas aleatorias para un sólo nodo inicial.

In [19]:
"""
La función r_walks tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
f, nodo inicial de tipo Int64
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz, el cual tiene igual probabilidad de avanzar 
hacia cualquiera de sus vecinos.
Regresa un arreglo que contiene todas las trayectorias que tomó el caminante aleatorio.
"""

function r_walks(M::Array{Int64,2}, f::Int64, steps::Int64, iter::Int64)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            if vecinos == []
                break
            else
                a = sample(vecinos)
                paths[i, p] = a
            s = a
            end
        end
        s = f
    end
    return paths 
end

r_walks (generic function with 1 method)

#### Pruebas r_walks

r_walks(mmulti, 1, 10, 10)

In [28]:
@time r_walks(mmulti, 1, 10, 1)

  0.000598 seconds (132 allocations: 257.063 KiB)


1×10 Array{Int64,2}:
 3  717  753  588  745  95  588  1217  739  629

In [29]:
@time r_walks(mmulti, 1, 100, 1)

  0.000291 seconds (49 allocations: 101.016 KiB)


1×100 Array{Int64,2}:
 647  336  1771  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0

In [30]:
@time r_walks(mmulti, 1, 100, 1)

  0.000582 seconds (147 allocations: 304.063 KiB)


1×100 Array{Int64,2}:
 721  123  764  706  301  670  146  67  …  0  0  0  0  0  0  0  0  0  0  0  0

In [13]:
@time r_walks(mmulti, 1, 10, 10)

  0.003977 seconds (936 allocations: 1.957 MiB)


10×10 Array{Int64,2}:
   8   726  749   458   689   538  588   173   690   643
 721   348  426    39   429   331  321  1491     0     0
 718   759  470    57   739   744  734   594   624   630
 647   765  287   875   465  2173    0     0     0     0
   3   112   49   782  1975     0    0     0     0     0
 450   685  450   287   254   642  407   914  2455     0
 718   590  723   313   316   317  311   317   315   545
 721  2836    0     0     0     0    0     0     0     0
 744  1306  622   739   686   734  729   309   430  1187
   8   726  747  2241     0     0    0     0     0     0

In [14]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 100, 10)

  0.005065 seconds (1.05 k allocations: 2.337 MiB)


10×100 Array{Int64,2}:
   3   618   398  1115   123     5  …  0  0  0  0  0  0  0  0  0  0  0  0
 718   531  2011     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 647   486   301    59    60  1093     0  0  0  0  0  0  0  0  0  0  0  0
 529  2778     0     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 718   766   644     3   726   747     0  0  0  0  0  0  0  0  0  0  0  0
   8   626    62   978  1591     0  …  0  0  0  0  0  0  0  0  0  0  0  0
   8   618   759     8   716   718     0  0  0  0  0  0  0  0  0  0  0  0
 450   531  2240     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   757   737   515   514   398     0  0  0  0  0  0  0  0  0  0  0  0
 647   718   759   491    50   475     0  0  0  0  0  0  0  0  0  0  0  0

In [27]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 500, 10)

  0.006047 seconds (1.44 k allocations: 3.053 MiB)


10×500 Array{Int64,2}:
 721   974   609   164   520   522  …  0  0  0  0  0  0  0  0  0  0  0  0
 529  2265     0     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   618   759   530   715   450     0  0  0  0  0  0  0  0  0  0  0  0
 647  1217   723   730   123   118     0  0  0  0  0  0  0  0  0  0  0  0
 744   515   764    39    94   426     0  0  0  0  0  0  0  0  0  0  0  0
 529  1301   744   739  1299  1298  …  0  0  0  0  0  0  0  0  0  0  0  0
 647   118  1771     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 718   528  1012   123   430   755     0  0  0  0  0  0  0  0  0  0  0  0
 529  1304   727   765   486   633     0  0  0  0  0  0  0  0  0  0  0  0
 529   190    48  1327    49   600     0  0  0  0  0  0  0  0  0  0  0  0

In [15]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 1000, 10)

  0.005895 seconds (1.19 k allocations: 2.596 MiB)


10×1000 Array{Int64,2}:
   3   734  729  2244    0     0     0  …  0  0  0  0  0  0  0  0  0  0  0  0
 529  2963    0     0    0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 744   515    5  1030  304  1085  2665     0  0  0  0  0  0  0  0  0  0  0  0
 647   739  486   633  724   723   748     0  0  0  0  0  0  0  0  0  0  0  0
 744     5  306  1730    0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 450   766  644     3  764   471   254  …  0  0  0  0  0  0  0  0  0  0  0  0
 647   314    3   757  452  1046  1218     0  0  0  0  0  0  0  0  0  0  0  0
 721   525  337   524  525   337   854     0  0  0  0  0  0  0  0  0  0  0  0
   8   726  724    56  301    80  2015     0  0  0  0  0  0  0  0  0  0  0  0
 529   762  123   759  529  1198  1308     0  0  0  0  0  0  0  0  0  0  0  0

In [17]:
#Cambio el nodo inicial
@time r_walks(mmulti, 986, 1000, 10)

  0.010220 seconds (1.76 k allocations: 3.748 MiB)


10×1000 Array{Int64,2}:
 104  1048   80   199   105  147  1114  …  0  0  0  0  0  0  0  0  0  0  0  0
 504   246  101   102   106   87   248     0  0  0  0  0  0  0  0  0  0  0  0
 104    92  476   478   770  476   478     0  0  0  0  0  0  0  0  0  0  0  0
  92    86  105  1457     0    0     0     0  0  0  0  0  0  0  0  0  0  0  0
 104   100  247    78   823   86  1047     0  0  0  0  0  0  0  0  0  0  0  0
  86   637  260   793    80  699   586  …  0  0  0  0  0  0  0  0  0  0  0  0
  86   274   87   929   106  268   504     0  0  0  0  0  0  0  0  0  0  0  0
 104  1646    0     0     0    0     0     0  0  0  0  0  0  0  0  0  0  0  0
  86   795   99   103  2313    0     0     0  0  0  0  0  0  0  0  0  0  0  0
  92   821   88    78   269   98   793     0  0  0  0  0  0  0  0  0  0  0  0

In [18]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 100)

  0.041242 seconds (9.38 k allocations: 19.772 MiB)


100×10 Array{Int64,2}:
 721   458   604  2123     0     0     0     0     0     0
 450   730   433   315   651   624   727   729   306    61
 744  1306   622   619   480   633   452   594  1250     3
 718   190  2255     0     0     0     0     0     0     0
 529  1297   685   687   590   377    64    65   996  1983
 647    57   747    58   470   118  1066  1761     0     0
 721   377   628   590   688   588   627   854   434    35
 721   633   450   759   744  1984     0     0     0     0
 744   545   647     3   624   486   715   450   685   723
   8   726  1433     0     0     0     0     0     0     0
 529  1002  1008  2553     0     0     0     0     0     0
 718   730   696  1308   123   453  1357    61   123  1218
 718   735   223   739    95   594   313   689   315   312
   ⋮                             ⋮                        
   3   764  1025   454   308   218  1134   902   222   377
 647  2245     0     0     0     0     0     0     0     0
 647   720   724   453     9  196

In [19]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 1000)

  0.594046 seconds (93.92 k allocations: 196.486 MiB, 37.11% gc time)


1000×10 Array{Int64,2}:
 450     6   589  1077  2635     0     0     0     0    0
   3   118  1365   321   132   523   415   545   753  759
 744  1306   622   739   528   633   747  1938     0    0
 647   545  2222     0     0     0     0     0     0    0
 721   982    14    11   857   982   981   857   379  982
 718   730  1307   685  2218     0     0     0     0    0
   3   545     7   594  1190   734   729    54   313  721
 450   287   690   118   443   340   362  2568     0    0
 718   304   452    11   982    14   854  2390     0    0
 744   715   737   531   725   223  1218   311  1747    0
 744   625   190   430   313   993   452  1011   123  739
   8   745   529  2247     0     0     0     0     0    0
 744   317   377    54    11   336    38   342  1784    0
   ⋮                             ⋮                       
   3   689   630   594   587   340   448  2191     0    0
   8   716   753   729   304   254   381   532   375  532
   8   757   450   722   531    95   626   545  

In [20]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 2000)

  1.082542 seconds (184.57 k allocations: 387.482 MiB)


2000×10 Array{Int64,2}:
 647   112  1689     0     0     0     0     0     0     0
   8   758   734   719   515    53  1217     5  1030   545
   8   745  1966     0     0     0     0     0     0     0
 529   739   759   485   729    57   747  1938     0     0
 647   756   531   123   739   287   545   190   630   590
   3   853   118   596    50   472  1240  2883     0     0
 647   651   730    53    55   315    94  1042  2590     0
 718    95   190   427  1338  1334    36  1430     0     0
   8   758   531    55   747    58   377   745   531  2240
   8   618   450   730   763   450   729   312   627   696
 744   766   644   452     5   482  1106   124  1590     0
 450    95   650   450   722   490   630   760   765   732
 718   590   633   529   627   452     5   529  1012   123
   ⋮                             ⋮                        
   8   726  1966     0     0     0     0     0     0     0
 721   485   752   484   481   744  1984     0     0     0
 744   515  1014   744   687   6

In [24]:
#Más pasos
@time r_walks(mmulti, 1, 40, 500)

  0.237406 seconds (62.33 k allocations: 131.999 MiB, 3.96% gc time)


500×40 Array{Int64,2}:
   3   602  1079   582    77    99   244  …    0    0   0    0    0     0  0
   3  1097   588  1499     0     0     0       0    0   0    0    0     0  0
 744   752   223   764   297   452  2963       0    0   0    0    0     0  0
 529   646   123    30  1543     0     0       0    0   0    0    0     0  0
 721   731   749   359  1843     0     0       0    0   0    0    0     0  0
   8   757   729  1297   727   739   759  …    0    0   0    0    0     0  0
 718   752   123   297   743   764  1301       0    0   0    0    0     0  0
   3   545   317   758    58   545   723       0    0   0    0    0     0  0
 744   515   484   377   437   312   529       0    0   0    0    0     0  0
 529   625   765   490  2245     0     0       0    0   0    0    0     0  0
 647   727   739   588    92   544    82  …    0    0   0    0    0     0  0
   8   716   753   759   627   687   765       0    0   0    0    0     0  0
 744     5   482   689   313   749   531       0    0

In [21]:
#Más pasos
@time r_walks(mmulti, 1, 100, 500)

  0.638309 seconds (68.73 k allocations: 145.453 MiB, 42.77% gc time)


500×100 Array{Int64,2}:
   3     8   626  1194  2840     0  …  0  0  0  0  0  0  0  0  0  0  0  0
   3  1291   315   304  1738     0     0  0  0  0  0  0  0  0  0  0  0  0
 529   450   729   633   730    95     0  0  0  0  0  0  0  0  0  0  0  0
 450   190   377   545  1218   529     0  0  0  0  0  0  0  0  0  0  0  0
 529  2265     0     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 718   190    39   339    51   339  …  0  0  0  0  0  0  0  0  0  0  0  0
   3   723  1217   529   515   482     0  0  0  0  0  0  0  0  0  0  0  0
 744   766   706   301   407    74     0  0  0  0  0  0  0  0  0  0  0  0
 721   501   314   759   486   513     0  0  0  0  0  0  0  0  0  0  0  0
   3   311   627  2222     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   745  2864     0     0     0  …  0  0  0  0  0  0  0  0  0  0  0  0
   8   758   726   618   753   730     0  0  0  0  0  0  0  0  0  0  0  0
   3   312  1187   314   384  1893     0  0  0  0  0  0  0  0  0  0  0  0
   ⋮          

In [25]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 1000)

  0.508268 seconds (129.85 k allocations: 276.035 MiB, 4.57% gc time)


1000×50 Array{Int64,2}:
 721  2836     0     0     0     0  …  0  0  0  0  0  0  0  0  0  0  0  0
   8   757   737   513   626   377     0  0  0  0  0  0  0  0  0  0  0  0
   8   618   718   762   123   223     0  0  0  0  0  0  0  0  0  0  0  0
 647   737   531   719   515   720     0  0  0  0  0  0  0  0  0  0  0  0
 718   123  1557     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   626   538  1305   452   731  …  0  0  0  0  0  0  0  0  0  0  0  0
 529   933   580  1530     0     0     0  0  0  0  0  0  0  0  0  0  0  0
 721   749   314   316   312    95     0  0  0  0  0  0  0  0  0  0  0  0
   3   340   458   426  1931     0     0  0  0  0  0  0  0  0  0  0  0  0
 721   759   731   747   725   223     0  0  0  0  0  0  0  0  0  0  0  0
 744   625   685  1015   624   314  …  0  0  0  0  0  0  0  0  0  0  0  0
 718   486   630   452  1305   589     0  0  0  0  0  0  0  0  0  0  0  0
 647  1252   720   450   685   471     0  0  0  0  0  0  0  0  0  0  0  0
   ⋮          

In [26]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 10000)

  5.125360 seconds (1.32 M allocations: 2.736 GiB, 4.58% gc time)


10000×50 Array{Int64,2}:
 647   633   630   450   685  1164  …  0  0  0  0  0  0  0  0  0  0  0  0
   8   626  1015  2218     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   726  1433     0     0     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   757   729  1046  1301   718     0  0  0  0  0  0  0  0  0  0  0  0
 718   993   624   530   633   482     0  0  0  0  0  0  0  0  0  0  0  0
   8   757   450   730   453   696  …  0  0  0  0  0  0  0  0  0  0  0  0
 744   739   531   515   304  1218     0  0  0  0  0  0  0  0  0  0  0  0
   3   645   450   685   450   190     0  0  0  0  0  0  0  0  0  0  0  0
 450   531   633   531   686   515     0  0  0  0  0  0  0  0  0  0  0  0
 647   625   528   190   640    72     0  0  0  0  0  0  0  0  0  0  0  0
 744   515     5   123   348   470  …  0  0  0  0  0  0  0  0  0  0  0  0
 529   735   223   454  1969     0     0  0  0  0  0  0  0  0  0  0  0  0
   8   618   753    95   624   449     0  0  0  0  0  0  0  0  0  0  0  0
   ⋮         

### Función random_walk

Llamaré a mi función que hace muchas iteraciones dentro de otra función que recorra todos mis nodos.

In [20]:
"""
La función random_walk tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz con igual probabilidad de avanzar 
hacia cualquiera de sus vecinos. Esta función recorre todos los nodos de la red como
nodos iniciales y sobre ellos itera para obtener el número de caminos que se le pidió.
Regresa un arreglo que contiene arreglos asociados a todas las trayectorias que tomó el 
caminante aleatorio para cada nodo inicial de la red.
"""

function random_walk(M::Array{Int64,2}, steps::Int64, iter::Int64)
    random_walks = []
    nodos = size(M, 1)
    for f in 1:nodos #aeropuertos
        paths = r_walks(M, f, steps, iter)
        push!(random_walks, paths)
    end
    random_walks
end

random_walk (generic function with 1 method)

### Pruebas random_walk en el multiplex

In [21]:
#5 iteraciones de un caminante aleatorio de 100 pasos sobre todos los nodos del multiplex 
@time random_walk(multiplex, 100, 5)

177.652581 seconds (19.17 M allocations: 38.668 GiB, 3.55% gc time)


3189-element Array{Any,1}:
 [724 20 … 262 310; 9 2282 … 555 1093; … ; 671 242 … 93 574; 670 2276 … 0 0]          
 [10 358 … 90 362; 4 764 … 730 1011; … ; 594 729 … 1631 1578; 9 1 … 189 1226]         
 [4 15 … 1130 2878; 14 729 … 304 1726; … ; 478 467 … 136 134; 725 232 … 0 0]          
 [2 10 … 0 0; 2737 594 … 1085 1378; … ; 9 189 … 220 886; 2846 9 … 260 180]            
 [4 730 … 1015 262; 8 90 … 4 2408; … ; 725 1532 … 190 1592; 7 193 … 469 51]           
 [2274 724 … 218 2532; 2274 682 … 1429 178; … ; 11 15 … 953 961; 727 189 … 469 109]   
 [5 7 … 135 1233; 5 671 … 1527 997; … ; 1531 1343 … 1852 71; 193 468 … 1785 894]      
 [730 2613 … 289 287; 730 163 … 949 950; … ; 351 349 … 370 1004; 5 2408 … 1301 1295]  
 [15 1531 … 594 496; 684 441 … 261 262; … ; 2742 4 … 2224 299; 998 9 … 467 453]       
 [352 14 … 177 1339; 232 1993 … 488 497; … ; 594 2033 … 872 512; 15 9 … 444 451]      
 [4 662 … 1205 1150; 6 4 … 1631 701; … ; 6 727 … 1194 393; 15 761 … 1414 656]         
 [4 339 … 4 1528

In [22]:
#5 iteraciones de un caminante aleatorio de 100 pasos sobre todos los nodos del multiplex 
prueba1 = @time random_walk(multiplex, 50, 2)

 14.410612 seconds (3.78 M allocations: 7.838 GiB, 4.64% gc time)


3189-element Array{Any,1}:
 [998 684 … 50 1988; 670 3084 … 2505 2500]
 [8 423 … 491 225; 9 2274 … 272 326]      
 [478 428 … 489 444; 244 9 … 58 1015]     
 [1012 2647 … 406 551; 2865 4 … 433 661]  
 [9 493 … 190 999; 8 90 … 1011 1014]      
 [232 671 … 1727 2031; 494 441 … 22 14]   
 [9 593 … 1121 199; 684 193 … 1475 1478]  
 [90 1023 … 2522 701; 728 14 … 315 1334]  
 [727 351 … 180 168; 183 424 … 602 598]   
 [683 682 … 2231 9; 4 242 … 2688 310]     
 [15 727 … 156 148; 9 997 … 259 316]      
 [15 358 … 305 284; 15 752 … 371 698]     
 [2274 682 … 1568 57; 2275 347 … 1357 132]
 ⋮                                        
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]                   
 [0 0 … 0 0; 0 0 … 0 0]    

In [23]:
#2 Caminatas de 50 pasos para nodo inicial 1
prueba1[1]

2×50 Array{Int64,2}:
 998   684  340  1184  963   911  1170  …   458  1993   458    53    50  1988
 670  3084  670   246    9  1861  1862     2503  2504  2503  2500  2505  2500

In [29]:
#2 Caminatas de 50 pasos para nodo inicial 3160
prueba1[3160]

2×50 Array{Int64,2}:
 3144  3160   310  2332  310  3163  …  449  220  448  479  470  451  1184
 3144  3160  3144  3160  310  1144       0    0    0    0    0    0     0

In [30]:
length(prueba1)

3189

In [32]:
size(prueba1)

(3189,)

In [31]:
length(prueba1[2])

100

In [39]:
s = size(prueba1[3160])

(2, 50)

In [40]:
s[1]

2

In [45]:
length(prueba1[3160])

100

In [57]:
#Tomo el renglón 2 del arreglo de 2 iteraciones de 50 pasos del nodo inicial 3160
prueba1[3160][2, :]

50-element Array{Int64,1}:
 3144
 3160
 3144
 3160
  310
 1144
  304
  279
  289
  180
  292
  278
 1668
    ⋮
  467
 1196
 1130
 3189
    0
    0
    0
    0
    0
    0
    0
    0

In [58]:
prueba1[3160][2, :][5]

310

### Función que cuenta longitud de la caminata antes de llegar a un cero

In [120]:
"""
La función walk_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función random_walk). Regresa un arreglo de arreglos, en donde cada entrada corresponde a la longitud de 
la caminata aleatoria antes de caer en un nodo con grado de salida 0.
"""

function walk_length(W)
    
    longitudes = Array[]
    c = 0
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v
        #@show i
        for j in 1:s
            #@show j
            #long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
            for k in 1:t
                #@show k
                
                if W[i][j, :][k] != 0 #W[i][j, :] #renglón a analizar
                    c += 1 
                    #@show c
                else
                    #@show c
                    long[j] = c 
                    #@show long #ant[i][j] = W[i][j, :][k - 1]
                    c = 0
                    break
                end
                #@show long
            end
            
            
        end
        push!(longitudes, long)
        #@show longitudes
        long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    end
    return longitudes
end

walk_length (generic function with 1 method)

In [59]:
d = [0  1  0
     1  0  1
     0  0  0];

In [83]:
#2 iteraciones de un caminante aleatorio de 10 pasos sobre todos los nodos del multiplex 
pruebad = @time random_walk(d, 10, 2)

  0.000015 seconds (141 allocations: 8.391 KiB)


3-element Array{Any,1}:
 [2 1 … 0 0; 2 1 … 0 0]
 [3 0 … 0 0; 3 0 … 0 0]
 [0 0 … 0 0; 0 0 … 0 0]

In [84]:
pruebad[1]

2×10 Array{Int64,2}:
 2  1  2  3  0  0  0  0  0  0
 2  1  2  1  2  3  0  0  0  0

In [121]:
prueba_length1 = @time walk_length(pruebad)

  0.071048 seconds (24.50 k allocations: 1.233 MiB)


3-element Array{Array,1}:
 [4, 6]
 [1, 1]
 [0, 0]

### Función que obtiene el promedio de la longitud de la caminata antes de llegar a un cero

In [128]:
"""
La función walk_av_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función walk_length). 
Regresa un arreglo con entradas correspondientes al promedio de las longitudes de 
las caminatas aleatorias para cada nodo de inicio antes de caer en un nodo con grado de salida 0.
"""

function walk_av_length(W)
   proms = []
    for i in 1:length(W)
        av = mean(W[i])
        push!(proms, av)
    end
    proms
end

walk_av_length (generic function with 1 method)

In [129]:
walk_av_length(prueba_length1)

3-element Array{Any,1}:
 5.0
 1.0
 0.0

### Función que da los nodos diferentes antes de llegar a un cero

In [153]:
"""
La función n_cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa los nodos diferentes a los que llega el caminante.
"""

function n_cobertura(W)
    
    cobert = []
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    #visit = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    visit = []
    
    for i in 1:v        
        for j in 1:s
            u = unique(W[i][j, :])
            push!(visit, u)
        end
        push!(cobert, visit)
        visit = []
    end
    return cobert
end

n_cobertura (generic function with 1 method)

In [152]:
pruebad[1]

2×10 Array{Int64,2}:
 2  1  2  3  0  0  0  0  0  0
 2  1  2  1  2  3  0  0  0  0

In [150]:
unique(pruebad[3][2, :])

1-element Array{Int64,1}:
 0

In [155]:
cob = n_cobertura(pruebad)

3-element Array{Any,1}:
 Any[[2, 1, 3, 0], [2, 1, 3, 0]]
 Any[[3, 0], [3, 0]]            
 Any[[0], [0]]                  

In [157]:
cob[1][1]

4-element Array{Int64,1}:
 2
 1
 3
 0

### Función que da el número de nodos diferentes, cobertura

In [158]:
"""
La función cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa el número de nodos diferentes a los que llega el caminante.
"""

function cobertura(W)
    
    cobert = []
    
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v        
        for j in 1:s
            l = length(W[i][j])
            long[j] = l
        end
        push!(cobert, long)
        long = zeros(Int64, s)
    end
    return cobert
end

cobertura (generic function with 1 method)

In [159]:
cobertura(cob)

3-element Array{Any,1}:
 [4, 4]
 [2, 2]
 [1, 1]

#### Pruebas random_walk

In [34]:
@time random_walk(mmulti, 10, 1)

  0.409549 seconds (107.86 k allocations: 214.736 MiB, 4.67% gc time)


3045-element Array{Any,1}:
 [3 470 … 0 0]        
 [651 471 … 0 0]      
 [608 1854 … 0 0]     
 [744 1984 … 0 0]     
 [306 747 … 0 0]      
 [2 2244 … 0 0]       
 [594 1164 … 458 1067]
 [716 718 … 0 0]      
 [1966 0 … 0 0]       
 [290 445 … 0 0]      
 [278 1678 … 0 0]     
 [375 520 … 163 1535] 
 [380 682 … 0 0]      
 ⋮                    
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          
 [0 0 … 0 0]          

In [35]:
#10 pasos, 10 iteraciones
@time random_walk(mmulti, 10, 10)

  3.925528 seconds (896.49 k allocations: 2.105 GiB, 4.50% gc time)


3045-element Array{Any,1}:
 [647 627 … 0 0; 721 287 … 0 0; … ; 744 624 … 0 0; 744 696 … 337 984]              
 [311 627 … 0 0; 651 624 … 0 0; … ; 311 312 … 0 0; 763 685 … 3 8]                  
 [1252 757 … 469 337; 651 718 … 0 0; … ; 458 338 … 0 0; 9 1252 … 525 382]          
 [744 545 … 514 301; 761 724 … 0 0; … ; 627 470 … 531 732; 685 34 … 0 0]           
 [529 1301 … 0 0; 1030 690 … 0 0; … ; 62 220 … 0 0; 123 430 … 0 0]                 
 [529 696 … 830 470; 1291 627 … 398 1217; … ; 761 588 … 337 1067; 449 743 … 0 0]   
 [594 1250 … 1305 732; 594 537 … 470 723; … ; 594 618 … 689 732; 594 630 … 933 721]
 [626 452 … 332 398; 757 531 … 0 0; … ; 757 531 … 0 0; 716 753 … 130 133]          
 [1218 304 … 286 1697; 588 1105 … 608 414; … ; 753 729 … 452 633; 1252 720 … 0 0]  
 [2536 0 … 0 0; 523 545 … 666 379; … ; 445 340 … 0 0; 445 1259 … 114 138]          
 [981 982 … 857 982; 857 982 … 854 2390; … ; 1958 0 … 0 0; 1957 0 … 0 0]           
 [375 854 … 379 988; 375 2397 … 0 0; … ; 375 2395

In [37]:
#50 pasos, 1 iteración
@time random_walk(mmulti, 50, 1)

  0.514614 seconds (121.39 k allocations: 285.316 MiB, 4.44% gc time)


3045-element Array{Any,1}:
 [744 696 … 0 0] 
 [123 7 … 0 0]   
 [450 287 … 0 0] 
 [529 720 … 0 0] 
 [1030 588 … 0 0]
 [484 625 … 0 0] 
 [594 3 … 0 0]   
 [618 1218 … 0 0]
 [753 735 … 0 0] 
 [141 1505 … 0 0]
 [982 857 … 0 0] 
 [375 381 … 0 0] 
 [431 13 … 0 0]  
 ⋮               
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     
 [0 0 … 0 0]     

In [38]:
#50 pasos, 10 iteraciones
@time random_walk(mmulti, 50, 10)

  5.352576 seconds (1.22 M allocations: 2.859 GiB, 4.58% gc time)


3045-element Array{Any,1}:
 [3 523 … 0 0; 718 6 … 0 0; … ; 8 626 … 0 0; 8 745 … 0 0]           
 [5 3 … 0 0; 647 529 … 0 0; … ; 6 723 … 0 0; 484 625 … 0 0]         
 [164 668 … 0 0; 452 626 … 0 0; … ; 340 692 … 0 0; 529 2247 … 0 0]  
 [627 297 … 0 0; 685 759 … 0 0; … ; 529 624 … 0 0; 618 304 … 0 0]   
 [482 129 … 0 0; 1030 545 … 0 0; … ; 529 4 … 0 0; 62 1529 … 0 0]    
 [727 95 … 0 0; 488 491 … 0 0; … ; 3 757 … 0 0; 529 630 … 0 0]      
 [594 734 … 0 0; 594 624 … 0 0; … ; 594 590 … 0 0; 594 625 … 0 0]   
 [726 761 … 0 0; 745 1218 … 0 0; … ; 726 1252 … 0 0; 726 1252 … 0 0]
 [592 752 … 0 0; 718 730 … 0 0; … ; 8 758 … 0 0; 450 729 … 0 0]     
 [2950 0 … 0 0; 291 1722 … 0 0; … ; 2951 0 … 0 0; 1852 0 … 0 0]     
 [532 14 … 0 0; 1957 0 … 0 0; … ; 1956 0 … 0 0; 375 379 … 0 0]      
 [375 857 … 0 0; 375 278 … 0 0; … ; 375 854 … 0 0; 375 381 … 0 0]   
 [380 376 … 0 0; 667 520 … 0 0; … ; 380 13 … 0 0; 431 13 … 0 0]     
 ⋮                                                                  
 [0 0 …

In [39]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 50)

 26.853834 seconds (6.09 M allocations: 14.285 GiB, 5.74% gc time)


3045-element Array{Any,1}:
 [718 765 … 0 0; 529 297 … 0 0; … ; 721 375 … 0 0; 718 95 … 0 0]     
 [720 1968 … 0 0; 651 482 … 0 0; … ; 720 686 … 0 0; 718 304 … 0 0]   
 [471 173 … 0 0; 450 6 … 0 0; … ; 623 2159 … 0 0; 608 1825 … 0 0]    
 [3 430 … 0 0; 5 3 … 0 0; … ; 618 2011 … 0 0; 592 5 … 0 0]           
 [95 627 … 0 0; 1030 287 … 0 0; … ; 95 190 … 0 0; 529 618 … 0 0]     
 [471 62 … 0 0; 753 759 … 0 0; … ; 4 744 … 0 0; 1 721 … 0 0]         
 [594 590 … 0 0; 594 618 … 0 0; … ; 594 627 … 0 0; 594 313 … 0 0]    
 [716 718 … 0 0; 726 531 … 0 0; … ; 726 718 … 0 0; 626 449 … 0 0]    
 [1291 301 … 0 0; 450 304 … 0 0; … ; 588 54 … 0 0; 1390 0 … 0 0]     
 [1393 0 … 0 0; 141 1504 … 0 0; … ; 1103 2686 … 0 0; 1103 2539 … 0 0]
 [857 379 … 0 0; 279 1679 … 0 0; … ; 534 431 … 0 0; 279 2948 … 0 0]  
 [375 381 … 0 0; 375 436 … 0 0; … ; 375 855 … 0 0; 375 532 … 0 0]    
 [375 520 … 0 0; 854 2390 … 0 0; … ; 854 2390 … 0 0; 380 376 … 0 0]  
 ⋮                                                             

In [40]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 100)

 54.101575 seconds (12.20 M allocations: 28.617 GiB, 6.12% gc time)


3045-element Array{Any,1}:
 [744 625 … 0 0; 529 480 … 0 0; … ; 744 317 … 0 0; 721 625 … 0 0]  
 [6 723 … 0 0; 123 592 … 0 0; … ; 482 630 … 0 0; 2244 0 … 0 0]     
 [623 2159 … 0 0; 608 363 … 0 0; … ; 1252 757 … 0 0; 651 528 … 0 0]
 [450 287 … 0 0; 3 337 … 0 0; … ; 762 763 … 0 0; 762 720 … 0 0]    
 [123 95 … 0 0; 592 129 … 0 0; … ; 592 630 … 0 0; 304 254 … 0 0]   
 [764 39 … 0 0; 651 724 … 0 0; … ; 753 739 … 0 0; 311 384 … 0 0]   
 [594 633 … 0 0; 594 1105 … 0 0; … ; 594 1250 … 0 0; 594 633 … 0 0]
 [745 739 … 0 0; 716 718 … 0 0; … ; 757 718 … 0 0; 757 753 … 0 0]  
 [720 686 … 0 0; 1392 0 … 0 0; … ; 720 737 … 0 0; 592 2218 … 0 0]  
 [2951 0 … 0 0; 1367 989 … 0 0; … ; 523 64 … 0 0; 415 1927 … 0 0]  
 [278 1265 … 0 0; 981 857 … 0 0; … ; 336 782 … 0 0; 857 982 … 0 0] 
 [375 458 … 0 0; 375 11 … 0 0; … ; 375 278 … 0 0; 375 2397 … 0 0]  
 [854 377 … 0 0; 854 336 … 0 0; … ; 666 375 … 0 0; 667 436 … 0 0]  
 ⋮                                                                 
 [0 0 … 0 0; 0 0 … 0 

### Redes artificiales

#### Ciclo

In [41]:
c1 = [0  1  0  0  1
      1  0  1  0  0
      0  1  0  1  0
      0  0  1  0  1
      1  0  0  1  0]

5×5 Array{Int64,2}:
 0  1  0  0  1
 1  0  1  0  0
 0  1  0  1  0
 0  0  1  0  1
 1  0  0  1  0

In [50]:
rc1 = @time random_walk(c1, 100, 10)

  0.001428 seconds (40.01 k allocations: 2.328 MiB)


5-element Array{Any,1}:
 [5 4 … 5 4; 2 3 … 4 3; … ; 5 1 … 4 3; 2 1 … 3 4]
 [3 2 … 5 1; 1 5 … 1 5; … ; 1 5 … 1 2; 3 2 … 2 3]
 [2 1 … 4 5; 4 3 … 4 3; … ; 4 5 … 2 1; 4 5 … 1 5]
 [3 4 … 4 5; 3 4 … 4 3; … ; 5 4 … 5 4; 5 4 … 3 4]
 [1 5 … 5 1; 4 3 … 4 3; … ; 1 5 … 3 4; 1 2 … 1 5]

In [51]:
#10 iteraciones de 100 pasos con nodo inicial 1 
rc1[1]

10×100 Array{Int64,2}:
 5  4  3  4  5  1  5  1  2  1  2  3  2  …  1  2  3  4  5  4  5  1  2  1  5  4
 2  3  2  3  4  3  4  3  2  3  4  3  4     1  2  1  5  4  3  4  5  4  3  4  3
 5  1  2  1  5  4  5  1  5  1  5  4  3     5  4  5  4  3  2  1  5  4  3  2  1
 5  1  5  1  5  1  5  4  5  1  2  3  2     2  1  5  1  5  1  5  1  2  3  4  3
 5  1  2  1  2  3  2  1  2  1  2  1  5     1  5  1  2  3  2  1  2  3  2  3  2
 2  3  4  5  1  2  1  2  3  2  3  2  3  …  5  1  5  1  2  3  2  3  2  3  4  5
 2  3  4  5  4  5  4  5  1  2  3  4  3     1  5  1  5  1  5  1  2  3  4  3  4
 5  4  5  1  2  1  2  3  2  3  2  1  2     1  5  1  2  3  2  1  5  1  2  3  2
 5  1  2  1  2  1  5  1  2  3  4  3  2     5  1  5  1  2  3  2  1  2  3  4  3
 2  1  2  1  5  1  2  3  4  5  1  2  1     4  5  1  2  3  4  5  1  5  4  3  4

In [52]:
#10 iteraciones de 100 pasos con nodo inicial 2
rc1[2]

10×100 Array{Int64,2}:
 3  2  1  5  4  5  4  3  4  3  2  1  5  …  4  3  4  3  2  3  4  3  2  1  5  1
 1  5  4  5  1  5  1  5  4  3  4  3  2     4  3  2  1  5  1  5  4  3  2  1  5
 1  2  1  5  1  5  4  5  1  2  3  4  5     3  2  3  4  3  2  1  2  1  2  1  2
 3  2  3  4  5  4  3  4  3  2  3  2  1     4  3  2  1  5  1  2  1  2  3  2  3
 3  4  3  2  1  5  1  5  1  2  1  2  3     5  1  5  1  5  1  5  4  3  2  3  2
 3  4  3  2  1  2  1  2  3  2  1  2  3  …  1  2  3  2  1  5  4  3  4  3  2  1
 3  4  3  4  3  2  3  2  1  2  1  5  1     2  3  2  3  2  1  5  1  2  1  5  4
 3  4  5  1  2  1  2  1  5  1  5  4  3     2  1  2  3  4  3  2  1  5  1  5  4
 1  5  1  2  3  2  1  5  1  2  1  5  4     4  3  4  5  4  3  4  3  4  5  1  2
 3  2  3  4  3  4  3  4  5  4  5  1  2     5  4  5  1  5  1  2  1  2  1  2  3

#### 2 ciclos

In [42]:
c2 = [0  1  1  0  0  0  
      1  0  1  0  0  0
      1  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  1
      0  0  0  0  1  1]

6×6 Array{Int64,2}:
 0  1  1  0  0  0
 1  0  1  0  0  0
 1  1  0  0  0  0
 0  0  0  0  1  1
 0  0  0  1  0  1
 0  0  0  0  1  1

In [53]:
rc2 = @time random_walk(c2, 100, 10)

  0.002250 seconds (48.01 k allocations: 2.793 MiB)


6-element Array{Any,1}:
 [2 1 … 3 2; 2 3 … 2 1; … ; 3 1 … 1 3; 2 3 … 2 3]
 [1 3 … 1 3; 1 2 … 2 3; … ; 3 2 … 3 2; 1 3 … 3 1]
 [1 2 … 1 3; 1 2 … 2 3; … ; 1 2 … 2 3; 1 3 … 1 2]
 [6 5 … 6 5; 6 5 … 5 6; … ; 5 6 … 6 6; 6 6 … 6 5]
 [6 5 … 5 6; 6 6 … 5 6; … ; 4 5 … 6 6; 4 6 … 6 6]
 [5 4 … 5 4; 6 6 … 6 6; … ; 5 4 … 5 6; 5 4 … 5 4]

In [54]:
#10 iteraciones de 100 pasos con nodo inicial 1 de una red de 2 ciclos
rc2[1]

10×100 Array{Int64,2}:
 2  1  2  1  3  2  3  2  3  1  2  3  1  …  1  2  1  3  2  1  2  1  3  2  3  2
 2  3  2  3  2  3  1  2  1  3  1  2  3     2  1  2  3  1  2  3  2  1  3  2  1
 2  1  3  1  3  1  3  1  3  1  3  2  1     1  3  1  3  1  2  1  2  3  2  3  2
 2  1  2  1  3  2  3  1  3  1  2  1  2     2  3  2  1  3  1  3  1  2  3  2  1
 2  3  2  1  2  1  2  1  2  3  2  1  2     1  2  1  3  2  1  3  1  2  1  2  1
 2  1  2  3  1  3  2  1  2  1  3  1  2  …  3  2  3  1  2  3  1  3  2  1  2  1
 3  2  1  3  1  3  2  3  1  3  1  2  1     1  3  2  3  2  1  3  2  1  3  1  2
 2  1  3  2  3  1  2  1  2  3  1  3  2     3  2  3  2  3  2  1  3  1  3  1  2
 3  1  2  1  3  1  2  1  3  1  3  2  1     1  2  1  2  3  2  1  3  2  3  1  3
 2  3  1  2  1  2  3  2  3  2  1  3  1     1  2  1  2  3  1  2  3  1  3  2  3

In [98]:
rc2[5]

10×100 Array{Int64,2}:
 4  6  4  5  4  6  4  6  4  5  4  5  4  …  4  6  4  6  4  5  4  5  4  5  4  6
 4  5  4  5  4  5  4  6  4  6  4  5  4     4  5  4  6  4  6  4  6  4  6  4  5
 4  6  4  5  4  6  4  5  4  5  4  5  4     4  6  4  5  4  5  4  6  4  6  4  6
 4  5  4  5  4  6  4  6  4  6  4  5  4     4  6  4  5  4  5  4  6  4  6  4  5
 4  5  4  6  4  5  4  5  4  6  4  5  4     4  6  4  6  4  6  4  6  4  6  4  6
 4  6  4  5  4  5  4  5  4  6  4  5  4  …  4  6  4  5  4  6  4  5  4  6  4  5
 4  6  4  6  4  5  4  6  4  6  4  5  4     4  6  4  6  4  6  4  6  4  6  4  5
 4  5  4  5  4  5  4  6  4  5  4  6  4     4  5  4  6  4  5  4  6  4  5  4  5
 4  6  4  6  4  5  4  6  4  5  4  5  4     4  6  4  6  4  6  4  5  4  5  4  5
 4  5  4  6  4  6  4  6  4  6  4  5  4     4  5  4  5  4  5  4  5  4  6  4  6

#### Eg2

In [43]:
t1 = [0  1  0  
      1  0  1 
      0  1  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  1  0

In [55]:
rt1 = @time random_walk(t1, 100, 10)

  0.001711 seconds (24.01 k allocations: 1.351 MiB)


3-element Array{Any,1}:
 [2 3 … 2 3; 2 3 … 2 1; … ; 2 3 … 2 3; 2 1 … 2 1]
 [1 2 … 1 2; 3 2 … 1 2; … ; 1 2 … 3 2; 3 2 … 1 2]
 [2 3 … 2 3; 2 1 … 2 1; … ; 2 3 … 2 1; 2 1 … 2 3]

In [56]:
#10 iteraciones de 100 pasos
rt1[1]

10×100 Array{Int64,2}:
 2  3  2  3  2  3  2  1  2  3  2  3  2  …  2  3  2  1  2  3  2  1  2  3  2  3
 2  3  2  3  2  1  2  3  2  1  2  1  2     2  3  2  1  2  1  2  1  2  3  2  1
 2  1  2  3  2  3  2  3  2  1  2  1  2     2  3  2  1  2  1  2  1  2  3  2  3
 2  3  2  3  2  3  2  3  2  3  2  1  2     2  3  2  3  2  1  2  1  2  1  2  3
 2  1  2  3  2  3  2  3  2  3  2  1  2     2  3  2  1  2  3  2  3  2  1  2  3
 2  1  2  3  2  1  2  3  2  3  2  3  2  …  2  3  2  3  2  3  2  1  2  1  2  1
 2  3  2  3  2  3  2  3  2  3  2  1  2     2  3  2  3  2  1  2  3  2  3  2  1
 2  1  2  1  2  3  2  3  2  3  2  1  2     2  3  2  1  2  3  2  1  2  3  2  1
 2  3  2  1  2  3  2  1  2  3  2  3  2     2  1  2  1  2  1  2  1  2  3  2  3
 2  1  2  3  2  3  2  1  2  1  2  1  2     2  1  2  1  2  1  2  1  2  3  2  1

In [44]:
t2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  0
      0  0  0  1  0  0]

6×6 Array{Int64,2}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  0  0  0
 0  0  0  0  1  1
 0  0  0  1  0  0
 0  0  0  1  0  0

In [58]:
rt2 = @time random_walk(t2, 100, 10)

  0.003299 seconds (48.01 k allocations: 2.793 MiB)


6-element Array{Any,1}:
 [2 1 … 2 1; 2 3 … 2 1; … ; 2 3 … 2 1; 2 3 … 2 1]
 [1 2 … 3 2; 1 2 … 3 2; … ; 1 2 … 3 2; 3 2 … 3 2]
 [2 3 … 2 3; 2 1 … 2 3; … ; 2 1 … 2 3; 2 3 … 2 1]
 [5 4 … 5 4; 6 4 … 5 4; … ; 5 4 … 5 4; 6 4 … 6 4]
 [4 6 … 4 5; 4 6 … 4 6; … ; 4 5 … 4 6; 4 5 … 4 6]
 [4 5 … 4 5; 4 5 … 4 5; … ; 4 6 … 4 5; 4 6 … 4 5]

In [59]:
#Nodo inicial 2
rt2[2]

10×100 Array{Int64,2}:
 1  2  3  2  3  2  1  2  3  2  1  2  3  …  1  2  1  2  3  2  3  2  3  2  3  2
 1  2  3  2  1  2  1  2  3  2  1  2  3     3  2  3  2  1  2  1  2  3  2  3  2
 1  2  1  2  3  2  1  2  3  2  1  2  1     3  2  1  2  1  2  1  2  1  2  1  2
 1  2  1  2  3  2  1  2  3  2  3  2  3     3  2  3  2  3  2  1  2  3  2  3  2
 1  2  1  2  1  2  1  2  1  2  1  2  1     3  2  3  2  3  2  3  2  1  2  3  2
 1  2  3  2  3  2  3  2  1  2  1  2  3  …  3  2  3  2  1  2  1  2  3  2  3  2
 1  2  3  2  3  2  1  2  1  2  3  2  3     1  2  1  2  3  2  3  2  3  2  1  2
 3  2  3  2  3  2  1  2  1  2  1  2  1     3  2  1  2  3  2  1  2  1  2  1  2
 1  2  1  2  3  2  3  2  3  2  3  2  1     3  2  3  2  3  2  3  2  1  2  3  2
 3  2  1  2  3  2  1  2  3  2  3  2  1     1  2  3  2  1  2  3  2  1  2  3  2

In [99]:
rt2[6]

10×100 Array{Int64,2}:
 4  5  4  5  4  6  4  5  4  6  4  6  4  …  4  5  4  5  4  5  4  5  4  5  4  5
 4  5  4  6  4  5  4  6  4  5  4  6  4     4  5  4  6  4  5  4  5  4  5  4  5
 4  5  4  6  4  6  4  6  4  6  4  5  4     4  5  4  5  4  6  4  6  4  5  4  6
 4  5  4  6  4  5  4  5  4  6  4  5  4     4  5  4  5  4  5  4  5  4  5  4  5
 4  5  4  5  4  6  4  5  4  6  4  5  4     4  6  4  5  4  5  4  5  4  6  4  5
 4  6  4  5  4  6  4  6  4  5  4  5  4  …  4  5  4  6  4  6  4  5  4  5  4  5
 4  5  4  5  4  5  4  5  4  6  4  5  4     4  6  4  5  4  5  4  5  4  5  4  5
 4  5  4  6  4  6  4  6  4  5  4  6  4     4  6  4  6  4  6  4  6  4  5  4  5
 4  6  4  6  4  5  4  6  4  5  4  6  4     4  5  4  5  4  6  4  6  4  6  4  5
 4  6  4  5  4  5  4  5  4  5  4  6  4     4  6  4  6  4  6  4  5  4  5  4  5

### Lineal

In [45]:
l1 = [0  1  0  0  
      1  0  1  0
      0  1  0  1
      0  0  1  0]

4×4 Array{Int64,2}:
 0  1  0  0
 1  0  1  0
 0  1  0  1
 0  0  1  0

In [60]:
rl1 = @time random_walk(l1, 100, 10)

  0.006833 seconds (32.01 k allocations: 1.801 MiB, 83.16% gc time)


4-element Array{Any,1}:
 [2 1 … 4 3; 2 3 … 4 3; … ; 2 3 … 4 3; 2 1 … 4 3]
 [3 2 … 3 2; 3 4 … 3 4; … ; 1 2 … 3 2; 3 2 … 3 4]
 [4 3 … 4 3; 4 3 … 2 3; … ; 2 1 … 2 1; 2 1 … 2 3]
 [3 2 … 3 2; 3 4 … 1 2; … ; 3 2 … 3 2; 3 2 … 3 2]

In [61]:
rl1[1]

10×100 Array{Int64,2}:
 2  1  2  1  2  1  2  1  2  3  2  3  2  …  2  3  4  3  4  3  4  3  2  3  4  3
 2  3  4  3  2  1  2  3  2  1  2  3  2     2  3  4  3  2  1  2  3  4  3  4  3
 2  1  2  1  2  3  2  3  2  1  2  1  2     2  3  4  3  2  1  2  3  2  3  2  3
 2  1  2  3  4  3  2  3  4  3  4  3  4     4  3  4  3  2  1  2  1  2  1  2  1
 2  1  2  3  2  1  2  1  2  3  4  3  2     2  3  4  3  4  3  4  3  4  3  2  1
 2  3  2  1  2  3  2  3  2  3  2  1  2  …  2  1  2  3  4  3  4  3  4  3  4  3
 2  1  2  1  2  3  2  1  2  1  2  1  2     2  3  2  1  2  1  2  1  2  1  2  3
 2  3  2  1  2  1  2  1  2  3  4  3  2     2  1  2  1  2  1  2  3  2  1  2  3
 2  3  2  1  2  1  2  1  2  3  4  3  2     4  3  4  3  2  1  2  3  4  3  4  3
 2  1  2  3  2  3  2  3  2  1  2  3  4     4  3  4  3  4  3  2  3  2  3  4  3

In [62]:
rl1[4]

10×100 Array{Int64,2}:
 3  2  1  2  3  2  1  2  3  2  1  2  3  …  3  4  3  4  3  2  1  2  3  4  3  2
 3  4  3  2  1  2  3  4  3  2  1  2  1     1  2  1  2  1  2  1  2  3  2  1  2
 3  4  3  4  3  2  3  2  1  2  3  2  1     3  4  3  2  3  4  3  2  3  4  3  4
 3  4  3  2  3  4  3  2  3  2  3  4  3     1  2  1  2  3  2  3  2  3  2  3  2
 3  4  3  2  3  2  3  4  3  4  3  2  3     3  4  3  2  1  2  3  2  3  4  3  2
 3  4  3  2  1  2  3  2  1  2  3  4  3  …  3  2  1  2  3  2  3  4  3  2  3  4
 3  2  1  2  3  4  3  4  3  4  3  4  3     1  2  1  2  1  2  1  2  1  2  3  2
 3  4  3  2  1  2  1  2  1  2  1  2  3     1  2  1  2  1  2  3  4  3  4  3  4
 3  2  3  2  3  4  3  4  3  4  3  4  3     1  2  3  2  1  2  3  2  3  4  3  2
 3  2  1  2  1  2  3  4  3  2  1  2  3     1  2  3  2  3  2  3  4  3  2  3  2

### 2 Lineal

In [46]:
l2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  0
      0  0  0  1  0  1
      0  0  0  0  1  0]

6×6 Array{Int64,2}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  0  0  0
 0  0  0  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [63]:
rl2 = @time random_walk(l2, 100, 10)

  0.003672 seconds (48.01 k allocations: 2.793 MiB)


6-element Array{Any,1}:
 [2 1 … 2 1; 2 1 … 2 3; … ; 2 1 … 2 1; 2 1 … 2 1]
 [3 2 … 1 2; 3 2 … 1 2; … ; 1 2 … 3 2; 1 2 … 3 2]
 [2 3 … 2 3; 2 1 … 2 1; … ; 2 3 … 2 1; 2 1 … 2 1]
 [5 4 … 5 6; 5 6 … 5 4; … ; 5 6 … 5 6; 5 6 … 5 6]
 [4 5 … 6 5; 4 5 … 6 5; … ; 4 5 … 6 5; 4 5 … 4 5]
 [5 6 … 5 4; 5 6 … 5 4; … ; 5 4 … 5 4; 5 4 … 5 6]

In [64]:
rl2[3]

10×100 Array{Int64,2}:
 2  3  2  3  2  1  2  1  2  1  2  3  2  …  2  3  2  1  2  3  2  3  2  3  2  3
 2  1  2  3  2  3  2  1  2  1  2  3  2     2  1  2  1  2  1  2  3  2  3  2  1
 2  1  2  1  2  1  2  1  2  1  2  1  2     2  1  2  3  2  1  2  3  2  3  2  1
 2  3  2  3  2  3  2  1  2  1  2  3  2     2  1  2  3  2  3  2  1  2  3  2  3
 2  3  2  1  2  1  2  1  2  3  2  3  2     2  1  2  1  2  3  2  3  2  1  2  1
 2  1  2  3  2  1  2  1  2  3  2  3  2  …  2  1  2  1  2  1  2  3  2  3  2  3
 2  3  2  1  2  3  2  3  2  3  2  1  2     2  3  2  3  2  3  2  3  2  3  2  1
 2  1  2  3  2  3  2  1  2  3  2  1  2     2  1  2  1  2  3  2  1  2  3  2  1
 2  3  2  1  2  1  2  1  2  3  2  1  2     2  1  2  1  2  1  2  3  2  3  2  1
 2  1  2  3  2  3  2  1  2  1  2  3  2     2  1  2  1  2  3  2  3  2  3  2  1

In [65]:
rl2[5]

10×100 Array{Int64,2}:
 4  5  4  5  4  5  6  5  4  5  4  5  4  …  6  5  6  5  4  5  6  5  4  5  6  5
 4  5  4  5  4  5  4  5  4  5  6  5  4     6  5  4  5  6  5  6  5  6  5  6  5
 6  5  4  5  4  5  6  5  6  5  6  5  4     6  5  4  5  6  5  6  5  6  5  6  5
 6  5  6  5  4  5  6  5  6  5  6  5  4     4  5  6  5  6  5  4  5  4  5  6  5
 6  5  4  5  6  5  4  5  4  5  4  5  6     6  5  4  5  4  5  4  5  4  5  6  5
 6  5  6  5  6  5  4  5  4  5  6  5  6  …  6  5  6  5  6  5  6  5  6  5  6  5
 6  5  6  5  4  5  6  5  4  5  6  5  6     4  5  4  5  4  5  6  5  4  5  6  5
 6  5  4  5  6  5  6  5  6  5  6  5  4     6  5  4  5  6  5  4  5  6  5  4  5
 4  5  4  5  4  5  6  5  6  5  6  5  6     6  5  4  5  4  5  6  5  6  5  6  5
 4  5  6  5  6  5  6  5  4  5  6  5  4     4  5  4  5  4  5  4  5  6  5  4  5

### Clica

In [47]:
g1 = [0  1  1  1  
      1  0  1  1
      1  1  0  1
      1  1  1  0]

4×4 Array{Int64,2}:
 0  1  1  1
 1  0  1  1
 1  1  0  1
 1  1  1  0

In [66]:
rg1 = @time random_walk(g1, 100, 10)

  0.001263 seconds (32.01 k allocations: 1.801 MiB)


4-element Array{Any,1}:
 [4 1 … 2 3; 3 2 … 3 1; … ; 3 2 … 3 2; 3 4 … 4 1]
 [4 2 … 4 2; 1 2 … 3 2; … ; 3 4 … 1 4; 4 3 … 3 4]
 [2 3 … 2 4; 4 1 … 2 3; … ; 1 4 … 4 3; 2 1 … 1 4]
 [3 4 … 2 4; 3 2 … 3 2; … ; 2 1 … 2 3; 3 2 … 3 2]

In [67]:
rg1[1]

10×100 Array{Int64,2}:
 4  1  4  3  1  4  2  3  4  1  3  2  3  …  1  2  1  3  1  3  1  2  3  4  2  3
 3  2  4  2  4  1  2  4  1  2  3  2  1     1  3  1  4  2  4  3  4  3  1  3  1
 4  1  3  2  3  4  3  2  3  1  4  3  4     4  3  1  3  2  4  3  1  3  2  4  1
 2  3  4  1  2  3  2  3  2  4  2  4  2     3  2  4  1  2  3  2  3  4  2  1  3
 3  4  3  4  1  4  2  1  3  4  1  3  2     4  3  4  3  4  2  1  3  1  3  2  4
 4  2  3  2  1  3  2  4  3  1  3  4  3  …  2  1  4  1  3  1  2  4  2  1  3  1
 4  3  4  2  1  2  3  1  3  2  3  4  1     4  1  2  3  2  1  3  1  4  3  2  4
 3  2  1  3  4  3  2  4  1  2  3  4  1     2  4  2  3  4  1  4  3  4  2  4  1
 3  2  1  2  3  2  1  4  1  3  1  3  2     4  1  4  3  1  2  3  4  1  2  3  2
 3  4  3  1  3  1  4  2  3  2  1  3  1     2  1  4  3  4  2  4  2  4  3  4  1

### 2 Clicas

In [48]:
g2 = [0  1  1  1  0  0  0  0  
      1  0  1  1  0  0  0  0
      1  1  0  1  0  0  0  0
      1  1  1  0  0  0  0  0
      0  0  0  0  0  1  1  1
      0  0  0  0  1  0  1  1
      0  0  0  0  1  1  0  1
      0  0  0  0  1  1  1  0]

8×8 Array{Int64,2}:
 0  1  1  1  0  0  0  0
 1  0  1  1  0  0  0  0
 1  1  0  1  0  0  0  0
 1  1  1  0  0  0  0  0
 0  0  0  0  0  1  1  1
 0  0  0  0  1  0  1  1
 0  0  0  0  1  1  0  1
 0  0  0  0  1  1  1  0

In [68]:
rg2 = @time random_walk(g2, 100, 10)

  0.002704 seconds (64.02 k allocations: 3.847 MiB)


8-element Array{Any,1}:
 [2 4 … 3 2; 4 1 … 4 2; … ; 4 2 … 2 4; 4 1 … 3 1]
 [3 1 … 2 1; 3 2 … 3 2; … ; 3 1 … 1 4; 4 1 … 3 2]
 [4 1 … 3 2; 1 3 … 2 3; … ; 4 1 … 2 3; 2 1 … 3 2]
 [1 4 … 3 4; 2 4 … 2 1; … ; 3 2 … 3 2; 2 1 … 2 4]
 [7 6 … 5 7; 8 5 … 7 8; … ; 8 6 … 7 6; 7 8 … 5 7]
 [7 6 … 8 5; 5 8 … 6 7; … ; 8 7 … 7 5; 7 8 … 7 8]
 [5 7 … 5 8; 8 5 … 5 7; … ; 8 5 … 5 6; 6 8 … 8 7]
 [7 8 … 5 7; 5 7 … 8 6; … ; 7 8 … 7 6; 7 6 … 7 5]

In [69]:
rg2[7]

10×100 Array{Int64,2}:
 5  7  6  8  5  6  7  5  7  5  7  6  7  …  8  7  5  8  5  6  8  6  7  6  5  8
 8  5  7  5  6  5  6  7  8  6  5  6  7     6  7  5  8  6  7  6  8  7  6  5  7
 6  5  8  6  7  8  6  5  6  8  7  5  6     6  5  8  7  8  6  7  6  5  8  5  7
 5  6  5  6  8  6  8  7  8  7  6  8  5     5  8  5  8  6  5  7  8  5  6  8  7
 8  6  8  5  7  6  8  5  6  5  6  8  5     6  7  6  7  6  5  7  8  5  8  5  8
 6  8  7  8  6  8  6  5  8  5  6  7  8  …  7  8  5  7  6  5  7  5  6  7  8  5
 8  7  5  6  5  7  8  5  8  7  8  5  6     6  7  6  5  6  8  7  5  6  5  6  5
 6  5  8  6  5  6  8  7  6  8  5  7  5     5  6  5  7  8  6  7  8  7  8  7  8
 8  5  6  5  8  7  5  8  5  6  7  8  6     7  6  7  8  5  6  5  7  8  6  5  6
 6  8  5  8  5  6  7  8  5  8  5  7  5     8  7  5  7  5  7  5  6  8  7  8  7

### Grafo dirigido

In [70]:
gd = [0  1  1  1  
      0  0  1  1
      0  1  0  0
      0  0  0  0]

4×4 Array{Int64,2}:
 0  1  1  1
 0  0  1  1
 0  1  0  0
 0  0  0  0

In [71]:
rgd = @time random_walk(gd, 100, 10)

  0.000056 seconds (1.35 k allocations: 107.688 KiB)


4-element Array{Any,1}:
 [3 2 … 0 0; 4 0 … 0 0; … ; 4 0 … 0 0; 4 0 … 0 0]
 [3 2 … 0 0; 4 0 … 0 0; … ; 4 0 … 0 0; 4 0 … 0 0]
 [2 4 … 0 0; 2 3 … 0 0; … ; 2 3 … 0 0; 2 3 … 0 0]
 [0 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 0 0; 0 0 … 0 0]

In [72]:
rgd[1]

10×100 Array{Int64,2}:
 3  2  4  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  4  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  3  2  3  2  3  2  4  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  4  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  4  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  4  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  3  2  4  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

In [74]:
rgd[2]

10×100 Array{Int64,2}:
 3  2  3  2  4  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  3  2  3  2  3  2  3  2  3  2  3     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  4  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  4  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 3  2  3  2  3  2  3  2  4  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  2  3  2  3  2  3  2  3  2  3  2  4     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

In [75]:
rgd[3]

10×100 Array{Int64,2}:
 2  4  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  3  2  3  2  3  2  4  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  4  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  4  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  4  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  4  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 2  4  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  3  2  3  2  4  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  3  2  4  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  3  2  4  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

In [76]:
rgd[4]

10×100 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0

In [95]:
in_degree(gd)

4×1 Array{Int64,2}:
 3
 2
 1
 0

In [12]:
"""
n_in_degree(M, n)

Función que obtiene el grado de entrada de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de entrada del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_in_degree(M::Array{Int64,2}, n::Int64)
    grado_entrada = sum(M[n, :])
end

n_in_degree (generic function with 1 method)

In [13]:
"""
in_degree(M)

Función que obtiene el grado de entrada de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de entrada de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function in_degree(M::Array)
    grados_entrada = sum(M, dims = 2)
end

in_degree (generic function with 1 method)

In [14]:
"""
n_out_degree(M, n)

Función que obtiene el grado de salida de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de salida del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_out_degree(M::Array{Int64,2}, n::Int64)
    grado_salida = sum(M[:, n])
end

n_out_degree (generic function with 1 method)

In [16]:
"""
out_degree(M)

Función que obtiene el grado de salida de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de salida de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function out_degree(M::Array)
    grados_salida = sum(M, dims = 1)
end

out_degree (generic function with 1 method)

In [ ]:
uhu = random_walk_f(c, 3, 2)

In [ ]:
uhu[1]

In [ ]:
#Ejemplo grande
eg = random_walk_f(c, 1000, 1000)

In [ ]:
eg[3]

In [ ]:
CSV.read("data/matriz_multi_uw.csv"; header = true, datacol = 2, types=Dict("col1"=>String))

In [ ]:
CSV.validate("data/matriz_multi_uw.csv"; header = true)

In [ ]:
#Por lo pronto probamos con este

random_walk_f(mmulti, 150, 1000)

In [ ]:
mmulti[7, :][594]

In [ ]:
#Checamos si encuentra los vecinos correctamente
findall(x -> x != 0, mmulti[1899, :])

In [ ]:
findall(x -> x != 0, mmulti[1000, :]) == []

In [ ]:
size(mmulti, 1)

In [ ]:
#Por lo pronto probamos con este


random_walk_f(mmulti, 10, 2)

In [ ]:
#Matriz fea
d = [0  1  0
     1  0  1
     0  0  0]  

In [ ]:
d

In [ ]:
random_walk_modif(d, 2, 5, 4)

In [ ]:
    rw = []
    #nodos = size(M, 1)
    for f in 1:size(mmulti, 1) #aeropuertos
        p = random_walk_modif(mmulti, f, 3, 3)
        push!(rw, p)
    end
    rw

In [ ]:
rw[2000]

In [ ]:
random_walk_f(mmulti, 5, 2)

In [ ]:
readdlm("data/matriz_multi_uw.csv", ',', header = true)

In [ ]:
?readdlm;

In [ ]:
homedir()

In [ ]:
pwd()

In [ ]:
?NamedArrays.setnames!

In [ ]:
colu = ["a", "b", "c"]
reng = ["hola", "hi", "hey"]

In [ ]:
xx = NamedArray(c, ["hola", "hi", "hey"])

In [ ]:
setnames!(a::NamedArray, names::Vector, dim::Int)

# NamedArray{T,N}(a::Array{T,N}, names::NTuple{N,Vector}, dimnames::NTuple{N})
x = NamedArray(Int[1 3; 2 4], ( ["A","B"], ["C","D"] ), ("ROWS","COLS"))

n = NamedArray(rand(2,4))
setnames!(n, ["one", "two"], 1)         # give the names "one" and "two" to the rows (dimension 1)

In [ ]:
function random_walkM3(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    @show nodos
    paths = zeros(Int64, (nodos*iter, steps)) 
    @show paths
    for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos 
        @show s
        m = s
        @show m
        for i = 1:iter
            @show i
            for p in 1:steps 
                @show p
                row = M[m, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                @show paths
                m = a
                @show m
            end
            m = s
            @show m
        end
    end
    paths
end

In [ ]:
function random_walk(M, steps)
    nodos = size(M, 1)
    paths = zeros(steps)
    for s in 1:nodos
        row = M[s, :]
        n_vecinos = sum(row)
        proba = 1/n_vecinos
        proba1 = 1/(n_vecinos - 1)
        p = rand()
        for i in 1:n_vecinos
            if proba< p <
        if 0 proba1 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

In [ ]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walk1d(n) #Función de caminante aleatorio en 1 dim.
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walkM(M, steps) #, iter)
    nodos = size(M, 1) #aeropuertos
    path = zeros(steps) 
    for i = 1 #for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos  
        @show i
        for p in 1:steps 
            @show p
            row = M[i, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            @show vecinos
            a = sample(vecinos)
            @show a
            path[p] = a
            i = a
        end
    end
    path
end

In [ ]:
function random_walkM2(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    for s = 1 #nodo inicial
        @show s
        for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
            @show i
            for p in 1:steps 
                #@show p
                row = M[s, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                s = a
            end
            s = 1
            @show paths
        end
    end
    return paths
end

In [ ]:
#Función 
function random_walk2(M, f, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            a = sample(vecinos)
            paths[i, p] = a
            s = a
        end
        s = f
    end
    return paths 
end

In [ ]:
#Eg. función
#b = random_walk2(c, 1, 50, 100)
k = random_walk2(c, 1, 10, 10)