# Random Walks en Redes Multicapa de Aerolíneas

In [3]:
using Pkg

In [4]:
Pkg.add("StatsBase")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  99.9 %0.0 %13.7 % [==========>                              ]  23.2 %36.8 %=====================>                   ]  50.5 %0 %              ]  64.7 % [================================>        ]  78.4 % Resolving package versions...
 Installed Compat ───── v2.1.0
 Installed Tokenize ─── v0.5.3
 Installed CSTParser ── v0.5.2
 Installed MacroTools ─ v0.5.0
  Updating `/Users/Yuriko/.julia/environments/v1.1/Project.toml`
  [2913bbd2] + StatsBase v0.29.0
  Updating `/Users/Yuriko/.julia/environments/v1.1/Manifest.toml`
  [00ebfdb7] + CSTParser v0.5.2
  [34da2185] ↑ Compat v2.0.0 ⇒ v2.1.0
  [1914dd2f] ↑ MacroTools v0.4.5 ⇒ v0.5.0
  [0796e94c] + Tokenize v0.5.3


In [5]:
using StatsBase

In [1]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 1  1  0

Array{Int64,2}

3

In [11]:
?dim

search: Dims DimensionMismatch ndims selectdim permutedims permutedims! divrem

Couldn't find dim
Perhaps you meant div, im, Dims, ndims, diff, edit, fdio, dump, do, big or cis


No documentation found.

Binding `dim` does not exist.


In [13]:
zeros(Int, size(c))

3×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0

In [27]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

multiplex (generic function with 4 methods)

In [61]:
function rw1d(n)
    path = zeros(n)
    for i in 1:n
        if rand()<= 1/2
            path[i] += 1
        else
            path[i] -= 1
        end
    end  
    path   
end

rw1d (generic function with 1 method)

In [63]:
rw1d(6)

6-element Array{Float64,1}:
  1.0
 -1.0
  1.0
  1.0
 -1.0
  1.0

In [70]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

random_walk1d (generic function with 1 method)

In [6]:
z = random_walk1d(5)

UndefVarError: UndefVarError: random_walk1d not defined

In [7]:
z = [0, 1, 1, 0, 1]

5-element Array{Int64,1}:
 0
 1
 1
 0
 1

In [14]:
h = 1:10

1:10

In [17]:
sample(h)

9

In [11]:
?sample

search: sample sample! samplepair wsample wsample!



```
sample([rng], a, [wv::AbstractWeights])
```

Select a single random element of `a`. Sampling probabilities are proportional to the weights given in `wv`, if provided.

Optionally specify a random number generator `rng` as the first argument (defaults to `Random.GLOBAL_RNG`).

---

```
sample([rng], a, [wv::AbstractWeights], n::Integer; replace=true, ordered=false)
```

Select a random, optionally weighted sample of size `n` from an array `a` using a polyalgorithm. Sampling probabilities are proportional to the weights given in `wv`, if provided. `replace` dictates whether sampling is performed with replacement and `order` dictates whether an ordered sample, also called a sequential sample, should be taken.

Optionally specify a random number generator `rng` as the first argument (defaults to `Random.GLOBAL_RNG`).

---

```
sample([rng], a, [wv::AbstractWeights], dims::Dims; replace=true, ordered=false)
```

Select a random, optionally weighted sample from an array `a` specifying the dimensions `dims` of the output array. Sampling probabilities are proportional to the weights given in `wv`, if provided. `replace` dictates whether sampling is performed with replacement and `order` dictates whether an ordered sample, also called a sequential sample, should be taken.

Optionally specify a random number generator `rng` as the first argument (defaults to `Random.GLOBAL_RNG`).

---

```
sample([rng], wv::AbstractWeights)
```

Select a single random integer in `1:length(wv)` with probabilities proportional to the weights given in `wv`.

Optionally specify a random number generator `rng` as the first argument (defaults to `Random.GLOBAL_RNG`).


In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walkM(M, steps)
    nodos = size(M, 1)
    path = zeros(steps)
    for s in 1:nodos
        for k in 1:steps
            row = M[s, :]
            vecinos = findall(row)
            n_vecinos = sum(row)
            u = sample(vecinos)
        end
    end
    paths
end

In [42]:
function random_walk(M, steps)
    nodos = size(M, 1)
    paths = zeros(steps)
    for s in 1:nodos
        row = M[s, :]
        n_vecinos = sum(row)
        proba = 1/n_vecinos
        proba1 = 1/(n_vecinos - 1)
        p = rand()
        for i in 1:n_vecinos
            if proba< p <
        if 0 proba1 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

LoadError: syntax: invalid identifier name "+="

In [125]:
x = rand() 
x

0.8660422658252163

In [102]:
v = (0.7,0.9)

(0.7, 0.9)

In [126]:
x
if x < 0.7
    println("false")
    elseif 0.7 < x < 0.9
        println("true")
    else 0.9 < x
        println("false")
end

true


In [107]:
x

0.8377880244908789

In [104]:
?is

search: include_string @int128_str isa isqrt isone isodd isnan isinf isdir

Couldn't find is
Perhaps you meant isa, cis, im, in, if, Dims, In, inv, IO, big, div, min or pi


No documentation found.

Binding `is` does not exist.


In [25]:
multiplex(a, b, c)

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  1  0

In [18]:
c = [0  1  0
 1  0  1
 0  1  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  1  0

In [22]:
findall(1, c)

MethodError: MethodError: no method matching findall(::Int64, ::Array{Int64,2})
Closest candidates are:
  findall(!Matched::Base.Fix2{typeof(in),#s72} where #s72<:Union{Real, Array{#s71,N} where N where #s71<:Real}, ::Array{#s70,N} where N where #s70<:Real) at array.jl:2257
  findall(!Matched::Base.Fix2{typeof(in),T} where T, ::Union{Tuple, AbstractArray}) at array.jl:2265
  findall(!Matched::Function, ::Any) at array.jl:1966
  ...

In [ ]:
# Buscamos vecinos

n0 = 1 # nodo inicial
vecinos = A[n_0, :]
p = 1/length(vecinos) # probabilidad


In [1]:
using CSV

┌ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1186


In [7]:
CSV.read("/Users/yuriko/Documents/UNAM/Tesis_Lic/m_multiplex.csv"; delim = ("""))

LoadError: syntax: incomplete: invalid string syntax

In [9]:
?CSV.read

`CSV.read(fullpath::Union{AbstractString,IO}, sink=DataFrame; kwargs...)` => `typeof(sink)`

Parses a delimited file into a Julia structure (a DataFrame by default, but any valid Tables.jl sink function can be provided).

Minimal error-reporting happens w/ `CSV.read` for performance reasons; for problematic csv files, try [`CSV.validate`](@ref) which takes exact same arguments as `CSV.read` and provides much more information for why reading the file failed.

Positional arguments:

  * `fullpath`: can be a file name (String) of the location of the csv file or `IO` object to read the csv from directly
  * `sink`: `DataFrame` by default, but may also be any other Tables.jl sink function

Supported keyword arguments include:

  * File layout options:

      * `header=1`: the `header` argument can be an `Int`, indicating the row to parse for column names; or a `Range`, indicating a span of rows to be combined together as column names; or an entire `Vector of Symbols` or `Strings` to use as column names
      * `normalizenames=false`: whether column names should be "normalized" into valid Julia identifier symbols
      * `datarow`: an `Int` argument to specify the row where the data starts in the csv file; by default, the next row after the `header` row is used
      * `skipto::Int`: similar to `datarow`, specifies the number of rows to skip before starting to read data
      * `footerskip::Int`: number of rows at the end of a file to skip parsing
      * `limit`: an `Int` to indicate a limited number of rows to parse in a csv file
      * `transpose::Bool`: read a csv file "transposed", i.e. each column is parsed as a row
      * `comment`: a `String` that occurs at the beginning of a line to signal parsing that row should be skipped
      * `use_mmap::Bool=!Sys.iswindows()`: whether the file should be mmapped for reading, which in some cases can be faster
  * Parsing options:
  * `missingstrings`, `missingstring`: either a `String`, or `Vector{String}` to use as sentinel values that will be parsed as `missing`; by default, only an empty field (two consecutive delimiters) is considered `missing`

      * `delim=','`: a `Char` or `String` that indicates how columns are delimited in a file
      * `ignorerepeated::Bool=false`: whether repeated (consecutive) delimiters should be ignored while parsing; useful for fixed-width files with delimiter padding between cells
      * `quotechar='"'`, `openquotechar`, `closequotechar`: a `Char` (or different start and end characters) that indicate a quoted field which may contain textual delimiters or newline characters
      * `escapechar='\'`: the `Char` used to escape quote characters in a text field
      * `dateformat::Union{String, Dates.DateFormat, Nothing}`: a date format string to indicate how Date/DateTime columns are formatted in a delimited file
      * `decimal`: a `Char` indicating how decimals are separated in floats, i.e. `3.14` used '.', or `3,14` uses a comma ','
      * `truestrings`, `falsestrings`: `Vectors of Strings` that indicate how `true` or `false` values are represented
  * Column Type Options:

      * `types`: a Vector or Dict of types to be used for column types; a Dict can map column index `Int`, or name `Symbol` or `String` to type for a column, i.e. Dict(1=>Float64) will set the first column as a Float64, Dict(:column1=>Float64) will set the column named column1 to Float64 and, Dict("column1"=>Float64) will set the column1 to Float64
      * `typemap::Dict{Type, Type}`: a mapping of a type that should be replaced in every instance with another type, i.e. `Dict(Float64=>String)` would change every detected `Float64` column to be parsed as `Strings`
      * `allowmissing=:all`: indicate how missing values are allowed in columns; possible values are `:all` - all columns may contain missings, `:auto` - auto-detect columns that contain missings or, `:none` - no columns may contain missings
      * `categorical::Union{Bool, Real}=false`: if `true`, columns detected as `String` are returned as a `CategoricalArray`; alternatively, the proportion of unique values below which `String` columns should be treated as categorical (for example 0.1 for 10%)
      * `strict::Bool=false`: whether invalid values should throw a parsing error or be replaced with missing values


In [10]:
CSV.read("/Users/yuriko/Documents/UNAM/Tesis_Lic/m_multiplex_df.csv")

3050×3051 DataFrames.DataFrame. Omitted printing of 3044 columns
│ Row  │ Column1 │ BCM    │ BGY    │ CLJ    │ IAS    │ LCA    │ LPL    │
│      │ String⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │ Int64⍰ │
├──────┼─────────┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1    │ BCM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 1      │
│ 2    │ BGY     │ 0      │ 0      │ 0      │ 0      │ 0      │ 1      │
│ 3    │ CLJ     │ 0      │ 1      │ 0      │ 1      │ 1      │ 2      │
│ 4    │ IAS     │ 0      │ 2      │ 0      │ 0      │ 1      │ 1      │
│ 5    │ LCA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 6    │ LPL     │ 0      │ 0      │ 0      │ 0      │ 1      │ 0      │
│ 7    │ OTP     │ 0      │ 1      │ 1      │ 1      │ 2      │ 1      │
│ 8    │ SBZ     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 9    │ TRN     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 10   │ TIA     │ 0      │ 2      │ 0      │ 0      │ 0      │ 0      │
⋮
│ 3040 │ NRA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3041 │ LSY     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3042 │ JCK     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3043 │ OOM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3044 │ MYA     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3045 │ EPR     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3046 │ HGD     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3047 │ ARM     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3048 │ OAG     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3049 │ CTL     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │
│ 3050 │ LRE     │ 0      │ 0      │ 0      │ 0      │ 0      │ 0      │