# Random Walks en Redes Multicapa de Aerolíneas

In [1]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 1  1  0

Array{Int64,2}

3

In [11]:
?dim

search: Dims DimensionMismatch ndims selectdim permutedims permutedims! divrem

Couldn't find dim
Perhaps you meant div, im, Dims, ndims, diff, edit, fdio, dump, do, big or cis


No documentation found.

Binding `dim` does not exist.


In [13]:
zeros(Int, size(c))

3×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0

In [27]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

multiplex (generic function with 4 methods)

In [61]:
function rw1d(n)
    path = zeros(n)
    for i in 1:n
        if rand()<= 1/2
            path[i] += 1
        else
            path[i] -= 1
        end
    end  
    path   
end

rw1d (generic function with 1 method)

In [63]:
rw1d(6)

6-element Array{Float64,1}:
  1.0
 -1.0
  1.0
  1.0
 -1.0
  1.0

In [70]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

random_walk1d (generic function with 1 method)

In [71]:
random_walk1d(5)

lugar = -1
lugar = -2
lugar = -1
lugar = 0
lugar = 1


6-element Array{Float64,1}:
  0.0
 -1.0
 -2.0
 -1.0
  0.0
  1.0

6-element Array{Float64,1}:
  1.0
 -1.0
  1.0
  1.0
 -1.0
 -1.0

In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [42]:
function random_walk(M)
    nodos = size(M, 1)
    paths = zeros(nodos)
    for s in 1:nodos
        vecinos = M[s, :]
        proba = 1/vecinos
        if 0 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

LoadError: syntax: invalid identifier name "+="

In [125]:
x = rand() 
x

0.8660422658252163

In [102]:
v = (0.7,0.9)

(0.7, 0.9)

In [126]:
x
if x < 0.7
    println("false")
    elseif 0.7 < x < 0.9
        println("true")
    else 0.9 < x
        println("false")
end

true


In [107]:
x

0.8377880244908789

In [104]:
?is

search: include_string @int128_str isa isqrt isone isodd isnan isinf isdir

Couldn't find is
Perhaps you meant isa, cis, im, in, if, Dims, In, inv, IO, big, div, min or pi


No documentation found.

Binding `is` does not exist.


In [25]:
multiplex(a, b, c)

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  1  0

In [ ]:
# Buscamos vecinos

n0 = 1 # nodo inicial
vecinos = A[n_0, :]
p = 1/length(vecinos) # probabilidad
