# Random Walks en Redes Multicapa de Aerolíneas

In [ ]:
using Pkg

In [ ]:
Pkg.add("Plots")

In [1]:
using StatsBase

┌ Info: Recompiling stale cache file /Users/yuriko/.julia/compiled/v1.1/StatsBase/EZjIG.ji for StatsBase [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91]
└ @ Base loading.jl:1184


In [2]:
using DelimitedFiles

In [3]:
using NamedArrays

┌ Info: Recompiling stale cache file /Users/yuriko/.julia/compiled/v1.1/NamedArrays/wPYCq.ji for NamedArrays [86f7a689-2022-50b4-a561-43c23ac3c673]
└ @ Base loading.jl:1184


In [4]:
using CSV

┌ Info: Recompiling stale cache file /Users/yuriko/.julia/compiled/v1.1/CSV/HHBkp.ji for CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1184


In [5]:
using LightGraphs

┌ Info: Recompiling stale cache file /Users/yuriko/.julia/compiled/v1.1/LightGraphs/Xm08G.ji for LightGraphs [093fc24a-ae57-5d10-9952-331d41423f4d]
└ @ Base loading.jl:1184


In [6]:
using Plots

┌ Info: Recompiling stale cache file /Users/yuriko/.julia/compiled/v1.1/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1184


In [7]:
cd("$(homedir())/Documents/UNAM/Tesis_Lic")

In [8]:
pwd()

"/Users/Yuriko/Documents/UNAM/Tesis_Lic"

In [9]:
a = [0  1  0
     1  0  1
     0  1  0]

b = [0  1  0
     0  0  1
     1  1  0]

c = [0  1  0
     1  0  1
     1  1  0]

d = [0  1  0
     1  0  1
     0  0  0];

In [10]:
multiplex17 = readdlm("data/matriz_multiplex_du.csv", ',')

3190×3190 Array{Any,2}:
 ""      "AER"   "ASF"   "CEK"   "DME"  …   "BSS"   "AEX"   "GCK"   "MGM"
 "AER"  0       0       0       1          0       0       0       0     
 "ASF"  0       0       0       1          0       0       0       0     
 "CEK"  0       0       0       1          0       0       0       0     
 "DME"  1       1       1       0          0       0       0       0     
 "EGO"  0       0       0       1       …  0       0       0       0     
 "GYD"  0       0       0       1          0       0       0       0     
 "KGD"  0       0       0       1          0       0       0       0     
 "KZN"  1       1       1       1          0       0       0       0     
 "LED"  1       1       1       1          0       0       0       0     
 "MRV"  0       1       0       1       …  0       0       0       0     
 "NBC"  0       0       0       1          0       0       0       0     
 "NJC"  0       0       0       1          0       0       0       0     
 ⋮            

In [11]:
multiplex17 = multiplex17[2:end, :];

In [12]:
multiplex17 = multiplex17[:, 2:end];

In [13]:
multiplex = convert(Array{Int64,2}, multiplex17)

3189×3189 Array{Int64,2}:
 0  0  0  1  0  0  0  1  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  0  1  1  1  1  1  1  1  1  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  1  1  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  1  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  1  1  1  1  1  1  1  0  1  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  1  0  0  1  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0

In [14]:
"""
n_in_degree(M, n)

Función que obtiene el grado de entrada de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de entrada del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_in_degree(M::Array{Int64,2}, n::Int64)
    grado_entrada = sum(M[n, :])
end

n_in_degree (generic function with 1 method)

In [15]:
"""
in_degree(M)

Función que obtiene el grado de entrada de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de entrada de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function in_degree(M::Array)
    grados_entrada = sum(M, dims = 2)
end

in_degree (generic function with 1 method)

In [16]:
"""
n_out_degree(M, n)

Función que obtiene el grado de salida de un cierto nodo n de la red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}
* n nodo a evaluar de tipo Int64

Resultado:
Grado de salida del nodo n representado por un valor numérico de tipo Int64

## Implementación

### Ejemplos
"""

function n_out_degree(M::Array{Int64,2}, n::Int64)
    grado_salida = sum(M[:, n])
end

n_out_degree (generic function with 1 method)

In [17]:
"""
out_degree(M)

Función que obtiene el grado de salida de una red representada por la matriz de adyacencia M.

Parámetros:
* M matriz de adyacencia que acepta un arreglo de tipo Array{Int64,2}

Resultado:
Devuelve un arreglo de tipo Array{Int64,2} que contiene los grados de salida de todos los nodos n de la red.

## Implementación

### Ejemplos
"""

function out_degree(M::Array)
    grados_salida = sum(M, dims = 1)
end

out_degree (generic function with 1 method)

In [18]:
in_degree(multiplex)

3189×1 Array{Int64,2}:
  17
   7
  14
 187
   9
  39
  10
  21
 110
  16
   7
   9
  10
   ⋮
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0

In [19]:
out_degree(multiplex)

1×3189 Array{Int64,2}:
 18  7  14  186  9  39  10  21  112  …  1  3  1  1  1  1  1  1  1  1  1  1

### Función r_walks

Caminatas aleatorias para un sólo nodo inicial.

In [20]:
"""
La función r_walks tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
f, nodo inicial de tipo Int64
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz, el cual tiene igual probabilidad de avanzar 
hacia cualquiera de sus vecinos.
Regresa un arreglo que contiene todas las trayectorias que tomó el caminante aleatorio.
"""

function r_walks(M::Array{Int64,2}, f::Int64, steps::Int64, iter::Int64)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            if vecinos == []
                break
            else
                a = sample(vecinos)
                paths[i, p] = a
            s = a
            end
        end
        s = f
    end
    return paths 
end

r_walks (generic function with 1 method)

#### Pruebas r_walks

r_walks(mmulti, 1, 10, 10)

In [ ]:
@time r_walks(mmulti, 1, 10, 1)

In [ ]:
@time r_walks(mmulti, 1, 100, 1)

In [ ]:
@time r_walks(mmulti, 1, 100, 1)

In [ ]:
@time r_walks(mmulti, 1, 10, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 100, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 500, 10)

In [ ]:
#Aumento el número de pasos
@time r_walks(mmulti, 1, 1000, 10)

In [ ]:
#Cambio el nodo inicial
@time r_walks(mmulti, 986, 1000, 10)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 100)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 1000)

In [ ]:
#Pocos pasos, más iteraciones
@time r_walks(mmulti, 1, 10, 2000)

In [ ]:
#Más pasos
@time r_walks(mmulti, 1, 40, 500)

In [ ]:
#Más pasos
@time r_walks(mmulti, 1, 100, 500)

In [ ]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 1000)

In [ ]:
#50 pasos y más iteraciones
@time r_walks(mmulti, 1, 50, 10000)

### Función random_walk

Llamaré a mi función que hace muchas iteraciones dentro de otra función que recorra todos mis nodos.

In [21]:
"""
La función random_walk tiene como parámetros:
M, matriz de adyacencia de tipo Array{Int64,2}
steps, número de pasos de tipo Int64
iter, número de iteraciones de tipo Int64.
La función crea un caminante aleatorio sobre la matriz con igual probabilidad de avanzar 
hacia cualquiera de sus vecinos. Esta función recorre todos los nodos de la red como
nodos iniciales y sobre ellos itera para obtener el número de caminos que se le pidió.
Regresa un arreglo que contiene arreglos asociados a todas las trayectorias que tomó el 
caminante aleatorio para cada nodo inicial de la red.
"""

function random_walk(M::Array{Int64,2}, steps::Int64, iter::Int64)
    random_walks = []
    nodos = size(M, 1)
    for f in 1:nodos #aeropuertos
        paths = r_walks(M, f, steps, iter)
        push!(random_walks, paths)
    end
    random_walks
end

random_walk (generic function with 1 method)

### Pruebas random_walk en el multiplex

In [ ]:
#5 iteraciones de un caminante aleatorio de 100 pasos sobre todos los nodos del multiplex 
@time random_walk(multiplex, 100, 5)

In [29]:
#2 iteraciones de un caminante aleatorio de 50 pasos sobre todos los nodos del multiplex 
prueba = @time random_walk(multiplex, 100, 2)

 29.164833 seconds (7.55 M allocations: 15.527 GiB, 5.90% gc time)


3189-element Array{Any,1}:
 [594 223 … 93 327; 594 489 … 1983 458]     
 [4 473 … 105 1316; 10 232 … 638 644]       
 [4 164 … 1685 1860; 728 15 … 448 223]      
 [22 672 … 473 1075; 469 1331 … 1049 193]   
 [7 1527 … 31 254; 753 352 … 949 333]       
 [2274 232 … 1197 1130; 494 1960 … 1854 663]
 [594 7 … 136 1008; 1756 7 … 1358 441]      
 [728 2797 … 1870 2636; 2 8 … 1468 599]     
 [478 2549 … 231 471; 351 8 … 700 697]      
 [340 2632 … 168 172; 683 682 … 2004 53]    
 [9 1227 … 304 180; 4 1532 … 1003 714]      
 [2274 12 … 268 323; 349 9 … 307 322]       
 [2274 1527 … 1874 232; 2275 14 … 1570 471] 
 ⋮                                          
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]                     
 [0 0 … 0 0; 0 0 … 0 0]     

In [30]:
#2 Caminatas de 100 pasos para nodo inicial 1
prueba[1]

2×100 Array{Int64,2}:
 594  223  1839  1957  594   304  418  …  564   93  587   93  100    93  327
 594  489   490   489  189  1027   60     208  395  338  467  479  1983  458

In [34]:
#2 Caminatas de 100 pasos para nodo inicial 3160
prueba[3160]

2×100 Array{Int64,2}:
 3144  310  2543   310  3143  1725  …  1342  453  187   57   594  684   57
  310  178   456  1531  1532   727     1085   40   43  441  1378  429  470

In [35]:
length(prueba)

3189

In [36]:
size(prueba)

(3189,)

In [37]:
length(prueba[2])

200

In [38]:
s = size(prueba[3160])

(2, 100)

In [39]:
s[1]

2

In [40]:
length(prueba[3160])

200

In [ ]:
#Tomo el renglón 2 del arreglo de 2 iteraciones de 50 pasos del nodo inicial 3160
prueba1[3160][2, :]

In [ ]:
prueba1[3160][2, :][5]

### Función que cuenta longitud de cada iteración de la caminata antes de llegar a un cero

In [41]:
"""
La función walk_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función random_walk). Regresa un arreglo de arreglos, en donde cada entrada corresponde a la longitud de 
la caminata aleatoria antes de caer en un nodo con grado de salida 0.
"""

function walk_length(W)
    
    longitudes = Array[]
    c = 0
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v
        #@show i
        for j in 1:s
            #@show j
            #long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
            for k in 1:t
                #@show k
                
                if W[i][j, :][k] != 0 #W[i][j, :] #renglón a analizar
                    c += 1 
                    #@show c
                else
                    #@show c
                    long[j] = c 
                    #@show long #ant[i][j] = W[i][j, :][k - 1]
                    c = 0
                    break
                end
                #@show long
            end
            
            
        end
        push!(longitudes, long)
        #@show longitudes
        long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    end
    return longitudes
end

walk_length (generic function with 1 method)

In [42]:
d = [0  1  0
     1  0  1
     0  0  0]

3×3 Array{Int64,2}:
 0  1  0
 1  0  1
 0  0  0

In [43]:
#2 iteraciones de un caminante aleatorio de 10 pasos sobre todos los nodos del multiplex 
pruebad = @time random_walk(d, 10, 2)

  0.000015 seconds (109 allocations: 6.578 KiB)


3-element Array{Any,1}:
 [2 3 … 0 0; 2 1 … 0 0]
 [3 0 … 0 0; 3 0 … 0 0]
 [0 0 … 0 0; 0 0 … 0 0]

In [44]:
pruebad[1]

2×10 Array{Int64,2}:
 2  3  0  0  0  0  0  0  0  0
 2  1  2  3  0  0  0  0  0  0

In [45]:
pruebad[2]

2×10 Array{Int64,2}:
 3  0  0  0  0  0  0  0  0  0
 3  0  0  0  0  0  0  0  0  0

In [46]:
pruebad[3]

2×10 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [47]:
prueba_lengthd = @time walk_length(pruebad)

  0.068246 seconds (71.69 k allocations: 3.711 MiB)


3-element Array{Array,1}:
 [2, 4]
 [1, 1]
 [0, 0]

### Función que obtiene el promedio de la longitud de la caminata por nodo antes de llegar a un cero

In [48]:
"""
La función walk_av_length tiene como parámetro W, que es un arreglo de arreglos (que se puede obtener de la 
función walk_length). 
Regresa un arreglo con entradas correspondientes al promedio de las longitudes de 
las caminatas aleatorias para cada nodo de inicio antes de caer en un nodo con grado de salida 0.
"""

function walk_av_length(W)
   proms = []
    for i in 1:length(W)
        av = mean(W[i])
        push!(proms, av)
    end
    proms
end

walk_av_length (generic function with 1 method)

In [49]:
walk_av_length(prueba_lengthd)

3-element Array{Any,1}:
 3.0
 1.0
 0.0

### Función que da los nodos diferentes en cada iteración de cada caminata antes de llegar a un cero

In [50]:
"""
La función n_cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa los nodos diferentes a los que llega el caminante.
"""

function n_cobertura(W)
    
    cobert = []
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    t = size(W[1], 2) #número de pasos
    #visit = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    visit = []
    
    for i in 1:v        
        for j in 1:s
            u = unique(W[i][j, :])
            push!(visit, u)
        end
        push!(cobert, visit)
        visit = []
    end
    return cobert
end

n_cobertura (generic function with 1 method)

In [61]:
cob = n_cobertura(pruebad)

3-element Array{Any,1}:
 Any[[2, 3, 0], [2, 1, 3, 0]]
 Any[[3, 0], [3, 0]]         
 Any[[0], [0]]               

In [53]:
cob[1][1]

3-element Array{Int64,1}:
 2
 3
 0

### Función que da el número de nodos diferentes, cobertura dado n_cobertura

In [54]:
"""
La función cobertura tiene como parámetro W que es un arreglo de arreglos.
Regresa el número de nodos diferentes a los que llega el caminante.
"""

#Tal vez falta llamar dentro de la función a la función n_cobertura

function cobertura(W)
    
    cobert = []
    
    v = length(W) #tamaño de la matriz, número de nodos
    s = size(W[1], 1) #lo puedo sacar, para todos es el mismo. Es el número de iteraciones
    long = zeros(Int64, s) #Arreglo de ceros de tamaño número de iteraciones
    
    for i in 1:v        
        for j in 1:s
            l = length(W[i][j])
            long[j] = l
        end
        push!(cobert, long)
        long = zeros(Int64, s)
    end
    return cobert
end

cobertura (generic function with 1 method)

In [55]:
cobertura(pruebad)

3-element Array{Any,1}:
 [1, 1]
 [1, 1]
 [1, 1]

In [62]:
cobertd = cobertura(cob)

3-element Array{Any,1}:
 [3, 4]
 [2, 2]
 [1, 1]

### Función que saca el promedio de las longitudes de (las iteraciones de) cada nodo

In [64]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function n_length_av(W)
    
    longitud = []

    for i in 1:length(W)
        l = mean(W[i])
        push!(longitud, l)
    end
    longitud
end

n_length_av (generic function with 1 method)

In [67]:
n_cobertd = n_length_av(cobertd)

3-element Array{Any,1}:
 3.5
 2.0
 1.0

### Función que obtiene el promedio de las longitudes promedio

In [71]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura y n_length_av

function length_av(W)

        mean(W)

end

length_av (generic function with 1 method)

In [72]:
length_av(n_cobertd)

2.1666666666666665

### Función que obtiene el máximo y mínimo de las longitudes

In [ ]:
"""

"""

#Tal vez falta llamar dentro de la función a la función n_cobertura y cobertura

function n_length_av(W)

    for i in 1:length(W)
        l = mean(W[i])
        push!(longitud, l)
    end
    longitud
end

#### Pruebas random_walk

In [ ]:
@time random_walk(mmulti, 10, 1)

In [ ]:
#10 pasos, 10 iteraciones
@time random_walk(mmulti, 10, 10)

In [ ]:
#50 pasos, 1 iteración
@time random_walk(mmulti, 50, 1)

In [ ]:
#50 pasos, 10 iteraciones
@time random_walk(mmulti, 50, 10)

In [ ]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 50)

In [ ]:
#50 pasos, 50 iteraciones
@time random_walk(mmulti, 50, 100)

### Redes artificiales

#### Ciclo

In [ ]:
c1 = [0  1  0  0  1
      1  0  1  0  0
      0  1  0  1  0
      0  0  1  0  1
      1  0  0  1  0]

In [ ]:
rc1 = @time random_walk(c1, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 1 
rc1[1]

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 2
rc1[2]

#### 2 ciclos

In [ ]:
c2 = [0  1  1  0  0  0  
      1  0  1  0  0  0
      1  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  1
      0  0  0  0  1  1]

In [ ]:
rc2 = @time random_walk(c2, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos con nodo inicial 1 de una red de 2 ciclos
rc2[1]

In [ ]:
rc2[5]

#### Eg2

In [ ]:
t1 = [0  1  0  
      1  0  1 
      0  1  0]

In [ ]:
rt1 = @time random_walk(t1, 100, 10)

In [ ]:
#10 iteraciones de 100 pasos
rt1[1]

In [ ]:
t2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  1
      0  0  0  1  0  0
      0  0  0  1  0  0]

In [ ]:
rt2 = @time random_walk(t2, 100, 10)

In [ ]:
#Nodo inicial 2
rt2[2]

In [ ]:
rt2[6]

### Lineal

In [ ]:
l1 = [0  1  0  0  
      1  0  1  0
      0  1  0  1
      0  0  1  0]

In [ ]:
rl1 = @time random_walk(l1, 100, 10)

In [ ]:
rl1[1]

In [ ]:
rl1[4]

### 2 Lineal

In [ ]:
l2 = [0  1  0  0  0  0  
      1  0  1  0  0  0
      0  1  0  0  0  0
      0  0  0  0  1  0
      0  0  0  1  0  1
      0  0  0  0  1  0]

In [ ]:
rl2 = @time random_walk(l2, 100, 10)

In [ ]:
rl2[3]

In [ ]:
rl2[5]

### Clica

In [ ]:
g1 = [0  1  1  1  
      1  0  1  1
      1  1  0  1
      1  1  1  0]

In [ ]:
rg1 = @time random_walk(g1, 100, 10)

In [ ]:
rg1[1]

### 2 Clicas

In [ ]:
g2 = [0  1  1  1  0  0  0  0  
      1  0  1  1  0  0  0  0
      1  1  0  1  0  0  0  0
      1  1  1  0  0  0  0  0
      0  0  0  0  0  1  1  1
      0  0  0  0  1  0  1  1
      0  0  0  0  1  1  0  1
      0  0  0  0  1  1  1  0]

In [ ]:
rg2 = @time random_walk(g2, 100, 10)

In [ ]:
rg2[7]

### Grafo dirigido

In [ ]:
gd = [0  1  1  1  
      0  0  1  1
      0  1  0  0
      0  0  0  0]

In [ ]:
rgd = @time random_walk(gd, 100, 10)

In [ ]:
rgd[1]

In [ ]:
rgd[2]

In [ ]:
rgd[3]

In [ ]:
rgd[4]

In [ ]:
in_degree(gd)

In [ ]:
uhu = random_walk_f(c, 3, 2)

In [ ]:
uhu[1]

In [ ]:
#Ejemplo grande
eg = random_walk_f(c, 1000, 1000)

In [ ]:
eg[3]

In [ ]:
CSV.read("data/matriz_multi_uw.csv"; header = true, datacol = 2, types=Dict("col1"=>String))

In [ ]:
CSV.validate("data/matriz_multi_uw.csv"; header = true)

In [ ]:
#Por lo pronto probamos con este

random_walk_f(mmulti, 150, 1000)

In [ ]:
mmulti[7, :][594]

In [ ]:
#Checamos si encuentra los vecinos correctamente
findall(x -> x != 0, mmulti[1899, :])

In [ ]:
findall(x -> x != 0, mmulti[1000, :]) == []

In [ ]:
size(mmulti, 1)

In [ ]:
#Por lo pronto probamos con este


random_walk_f(mmulti, 10, 2)

In [ ]:
#Matriz fea
d = [0  1  0
     1  0  1
     0  0  0]  

In [ ]:
d

In [ ]:
random_walk_modif(d, 2, 5, 4)

In [ ]:
    rw = []
    #nodos = size(M, 1)
    for f in 1:size(mmulti, 1) #aeropuertos
        p = random_walk_modif(mmulti, f, 3, 3)
        push!(rw, p)
    end
    rw

In [ ]:
rw[2000]

In [ ]:
random_walk_f(mmulti, 5, 2)

In [ ]:
readdlm("data/matriz_multi_uw.csv", ',', header = true)

In [ ]:
?readdlm;

In [ ]:
?NamedArrays.setnames!

In [ ]:
colu = ["a", "b", "c"]
reng = ["hola", "hi", "hey"]

In [ ]:
xx = NamedArray(c, ["hola", "hi", "hey"])

In [ ]:
setnames!(a::NamedArray, names::Vector, dim::Int)

# NamedArray{T,N}(a::Array{T,N}, names::NTuple{N,Vector}, dimnames::NTuple{N})
x = NamedArray(Int[1 3; 2 4], ( ["A","B"], ["C","D"] ), ("ROWS","COLS"))

n = NamedArray(rand(2,4))
setnames!(n, ["one", "two"], 1)         # give the names "one" and "two" to the rows (dimension 1)

In [ ]:
function random_walkM3(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    @show nodos
    paths = zeros(Int64, (nodos*iter, steps)) 
    @show paths
    for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos 
        @show s
        m = s
        @show m
        for i = 1:iter
            @show i
            for p in 1:steps 
                @show p
                row = M[m, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                @show paths
                m = a
                @show m
            end
            m = s
            @show m
        end
    end
    paths
end

In [ ]:
function random_walk(M, steps)
    nodos = size(M, 1)
    paths = zeros(steps)
    for s in 1:nodos
        row = M[s, :]
        n_vecinos = sum(row)
        proba = 1/n_vecinos
        proba1 = 1/(n_vecinos - 1)
        p = rand()
        for i in 1:n_vecinos
            if proba< p <
        if 0 proba1 < x < proba
            
            elseif proba < x < 2*proba
                
            else 0.9 < x
                
        end
    end
    paths
end

In [ ]:
# Matriz de adyacencia del multiplex

function multiplex(lista)
    matriz = Array{Int, 2}() # Creo una matriz vacía para el multiplex
    for i in 1:length(lista)
        for j in 1:length(lista)
            if lista[i][j] == 0
                matriz[j] = 0
            else
                matriz[j] = 1
            end
        end
    end
    matriz
end

In [ ]:
function random_walk1d(n)
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walk1d(n) #Función de caminante aleatorio en 1 dim.
    paths = zeros(n+1)
    lugar = 0
    for s in 1:n
        if rand() <= 1/2
            lugar -= 1
            @show lugar
            paths[s+1] = lugar
        else
            lugar += 1
            @show lugar
            paths[s+1] = lugar
        end
    end
    paths
end

In [ ]:
function random_walkM(M, steps) #, iter)
    nodos = size(M, 1) #aeropuertos
    path = zeros(steps) 
    for i = 1 #for s in 1:nodos #Toma como nodo de inicio todos los aeropuertos  
        @show i
        for p in 1:steps 
            @show p
            row = M[i, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            @show vecinos
            a = sample(vecinos)
            @show a
            path[p] = a
            i = a
        end
    end
    path
end

In [ ]:
function random_walkM2(M, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    for s = 1 #nodo inicial
        @show s
        for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
            @show i
            for p in 1:steps 
                #@show p
                row = M[s, :] #Renglón correspondiente al nodo s
                vecinos = findall(x -> x != 0, row)
                @show vecinos
                a = sample(vecinos)
                @show a
                paths[i, p] = a
                s = a
            end
            s = 1
            @show paths
        end
    end
    return paths
end

In [ ]:
#Función 
function random_walk2(M, f, steps, iter)
    nodos = size(M, 1) #aeropuertos
    paths = zeros(Int64, (iter, steps)) 
    s = f
    for i in 1:iter #Toma como nodo de inicio todos los aeropuertos  
        for p in 1:steps 
            row = M[s, :] #Renglón correspondiente al nodo s
            vecinos = findall(x -> x != 0, row)
            a = sample(vecinos)
            paths[i, p] = a
            s = a
        end
        s = f
    end
    return paths 
end

In [ ]:
#Eg. función
#b = random_walk2(c, 1, 50, 100)
k = random_walk2(c, 1, 10, 10)